<?php
namespace App\Services;
use App\Models\SaasBackup;use Illuminate\Support\Facades\{DB,Schema,Storage};use ZipArchive;
class SecureBackupService{
 public function create(SaasBackup$record,?array$campusIds=null):SaasBackup{$record->update(['status'=>'Processing','error_message'=>null]);$tmp=tempnam(sys_get_temp_dir(),'erp_backup_');$zipPath=$tmp.'.zip';@unlink($tmp);$zip=new ZipArchive();if($zip->open($zipPath,ZipArchive::CREATE)!==true)throw new\RuntimeException('Cannot create backup archive.');$password=(string)config('app.key');$type=strtolower($record->type);
  if(str_contains($type,'database')||str_contains($type,'full')){$payload=['driver'=>DB::getDriverName(),'created_at'=>now()->toIso8601String(),'tenant_scoped'=>(bool)$campusIds,'tables'=>[]];foreach(Schema::getTables()as$meta){$table=$meta['name'];if($table==='sessions')continue;$q=DB::table($table);if($campusIds){if(Schema::hasColumn($table,'campus_id'))$q->whereIn('campus_id',$campusIds);elseif($table==='campuses')$q->whereIn('id',$campusIds);else continue;}$payload['tables'][$table]=$q->get()->map(fn($x)=>(array)$x)->all();}$zip->addFromString('database.json',json_encode($payload,JSON_UNESCAPED_UNICODE));$zip->setEncryptionName('database.json',ZipArchive::EM_AES_256,$password);}
  if(!$campusIds&&(str_contains($type,'files')||str_contains($type,'full')))foreach(['private'=>storage_path('app/private'),'public'=>storage_path('app/public')]as$label=>$root){if(!is_dir($root))continue;foreach(new\RecursiveIteratorIterator(new\RecursiveDirectoryIterator($root,\FilesystemIterator::SKIP_DOTS))as$file){if(!$file->isFile()||str_contains(str_replace('\\','/',$file->getPathname()),'/backups/'))continue;$name='files/'.$label.'/'.str_replace('\\','/',substr($file->getPathname(),strlen($root)+1));$zip->addFile($file->getPathname(),$name);$zip->setEncryptionName($name,ZipArchive::EM_AES_256,$password);}}
  $zip->close();$contents=file_get_contents($zipPath);$path=$record->file_name;$disk=config('erp.backup_disk','backup');Storage::disk($disk)->put($path,$contents);@unlink($zipPath);return tap($record)->update(['status'=>'Completed','disk'=>$disk,'path'=>$path,'file_size'=>round(strlen($contents)/1048576,2).' MB','checksum'=>hash('sha256',$contents),'encrypted'=>true,'completed_at'=>now()]);}
 public function verify(SaasBackup$b):bool{if(!$b->path||!Storage::disk($b->disk)->exists($b->path))return false;$ok=hash_equals((string)$b->checksum,hash('sha256',Storage::disk($b->disk)->get($b->path)));if($ok)$b->update(['verified_at'=>now()]);return$ok;}}
