<?php
namespace App\Services;
use App\Models\{Exam,ExamMark,Invoice,Student,StudentAttendance};use Carbon\Carbon;
class SmsCampaignService {
 public function send(string $type,array $options,int $userId):array {$sent=0;$skipped=0;
  if($type==='absent'){$rows=StudentAttendance::with('student.guardian')->whereDate('attendance_date',$options['date'])->where('status','absent')->when($options['class_id']??null,fn($q,$id)=>$q->where('school_class_id',$id))->when($options['section_id']??null,fn($q,$id)=>$q->where('section_id',$id))->get();foreach($rows as $row){$student=$row->student;$phone=$this->phone($student);if(!$phone){$skipped++;continue;}$message="সম্মানিত অভিভাবক, আপনার সন্তান {$student->first_name} ".Carbon::parse($options['date'])->format('d-m-Y')." তারিখে স্কুলে অনুপস্থিত। অনুগ্রহ করে স্কুলে যোগাযোগ করুন।";$this->dispatch($student,$phone,$message,'attendance',"absent:{$row->id}",$userId)?$sent++:$skipped++;}}
  elseif($type==='exam_result'){$exam=Exam::findOrFail($options['exam_id']);$groups=ExamMark::with(['student.guardian','subject:id,name'])->where('exam_id',$exam->id)->get()->groupBy('student_id');foreach($groups as $marks){$student=$marks->first()->student;$phone=$this->phone($student);if(!$phone){$skipped++;continue;}$details=$marks->map(fn($m)=>($m->subject?->name??'Subject').': '.($m->marks_obtained??'-').($m->grade?' ('.$m->grade.')':''))->join(', ');$message="{$student->first_name}-এর {$exam->name} ফলাফল: {$details}. মোট: ".$marks->sum('marks_obtained')."।";$this->dispatch($student,$phone,$message,'exam_result',"exam:{$exam->id}:student:{$student->id}",$userId)?$sent++:$skipped++;}}
  elseif($type==='fee_due'){$students=Student::with('guardian')->whereHas('invoices',fn($q)=>$q->whereIn('status',['Unpaid','Partial']))->get();foreach($students as $student){$due=Invoice::where('student_id',$student->id)->whereIn('status',['Unpaid','Partial'])->get()->sum(fn($i)=>max(0,$i->amount+$i->fine-$i->discount-$i->paid_amount));$phone=$this->phone($student);if(!$phone||$due<=0){$skipped++;continue;}$message="সম্মানিত অভিভাবক, {$student->first_name}-এর মোট বকেয়া ৳".number_format($due,2)."। অনুগ্রহ করে নির্ধারিত সময়ে পরিশোধ করুন।";$this->dispatch($student,$phone,$message,'fee_due',"fee-due:{$student->id}:".now()->format('Y-m-d'),$userId)?$sent++:$skipped++;}}
  else {$students=Student::with('guardian')->when($options['class_id']??null,fn($q,$id)=>$q->whereHas('currentEnrollment',fn($e)=>$e->where('class_id',$id)))->get();foreach($students as $student){$phone=$this->phone($student);if(!$phone){$skipped++;continue;}$message=str_replace(['{student}','{date}'],[$student->first_name,now()->format('d-m-Y')],$options['message']);$this->dispatch($student,$phone,$message,$type,$type.':'.$student->id.':'.now()->format('Y-m-d').':'.sha1($message),$userId)?$sent++:$skipped++;}}
  return compact('sent','skipped');}
 private function phone(Student $s):?string{return $s->guardian?->father_phone?:$s->guardian?->mother_phone?:$s->phone;}
 private function dispatch(Student $s,string $phone,string $message,string $category,string $key,int $userId):bool{return SmsService::send($phone,$message,['campus_id'=>$s->campus_id,'recipient_name'=>trim($s->first_name.' '.$s->last_name),'recipient_type'=>'student','recipient_id'=>$s->id,'reference_key'=>$key,'category'=>$category,'sent_by'=>$userId]);}
}
