import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Icon from '@/Components/Icons';
import {Head,Link} from '@inertiajs/react';

const money=n=>`৳ ${Number(n||0).toLocaleString('en-BD')}`;
const go=n=>{try{return route().has(n)?route(n):'#'}catch{return '#'}};
const Panel=({title,action,children})=><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center justify-between border-b px-5 py-4"><h2 className="font-bold text-slate-900">{title}</h2>{action}</header>{children}</section>;
const Metric=({title,value,detail,tone='emerald'})=><div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{title}</p><p className={`mt-3 text-2xl font-black ${tone==='rose'?'text-rose-700':tone==='amber'?'text-amber-700':'text-emerald-800'}`}>{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div>;

export default function FinanceDashboard({finance}) {
 const m=finance.metrics,max=Math.max(1,...finance.trend.flatMap(x=>[Number(x.income),Number(x.expense)]));
 return <AuthenticatedLayout><Head title="Finance Dashboard"/><main className="space-y-6 py-4 sm:py-6">
  <section className="rounded-3xl bg-gradient-to-br from-indigo-950 via-slate-900 to-emerald-900 p-7 text-white shadow-xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-300">Finance control center · {finance.today}</p><h1 className="mt-2 text-3xl font-black">Welcome, {finance.name}</h1><p className="mt-2 text-sm text-slate-300">{finance.designation} · {finance.department}</p><div className="mt-5 flex flex-wrap gap-2">{[['Collect fee','admin.studentfees.index'],['Invoices','admin.fees.invoices'],['Income / expense','admin.fees.ledger'],['Financial report','admin.reports.financial-summary']].map(([x,r])=><Link key={x} href={go(r)} className="rounded-xl bg-white/10 px-4 py-2 text-sm font-bold ring-1 ring-white/15 hover:bg-white/20">{x}</Link>)}</div></section>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Collection today" value={money(m.today_collection)} detail={`This month ${money(m.month_collection)}`}/><Metric title="Expense today" value={money(m.today_expense)} detail={`This month ${money(m.month_expense)}`} tone="amber"/><Metric title="Outstanding dues" value={money(m.total_due)} detail={`${m.overdue_count} overdue invoices`} tone="rose"/><Metric title="Gateway attention" value={m.pending_online} detail={`${m.failed_online} failed today`} tone="amber"/></div>
  <div className="grid gap-6 xl:grid-cols-3"><Panel title="Six-month cash flow" action={<Link href={go('admin.reports.financial-summary')} className="text-xs font-bold text-indigo-700">Full report →</Link>}><div className="p-5 xl:col-span-1"><div className="mb-3 flex gap-4 text-xs"><span className="text-emerald-700">● Income</span><span className="text-amber-600">● Expense</span></div><div className="flex h-52 items-end gap-3">{finance.trend.map(x=><div key={x.label} className="flex h-full flex-1 flex-col justify-end"><div className="flex h-44 items-end justify-center gap-1"><div title={money(x.income)} className="w-4 rounded-t bg-emerald-500" style={{height:`${Math.max(3,x.income/max*100)}%`}}/><div title={money(x.expense)} className="w-4 rounded-t bg-amber-400" style={{height:`${Math.max(3,x.expense/max*100)}%`}}/></div><small className="mt-2 text-center text-slate-500">{x.label}</small></div>)}</div></div></Panel>
   <Panel title="Overdue invoices"><div className="divide-y">{finance.overdueInvoices.map(x=><Link href={go('admin.studentfees.index')} key={x.id} className="flex justify-between p-4 text-sm hover:bg-slate-50"><span><b>{x.student}</b><small className="block text-slate-500">{x.invoice_no} · due {x.due_date}</small></span><b className="text-rose-700">{money(x.due)}</b></Link>)}{!finance.overdueInvoices.length&&<p className="p-8 text-center text-sm text-slate-400">No overdue invoice.</p>}</div></Panel>
   <Panel title="Gateway transactions"><div className="divide-y">{finance.transactions.map(x=><Link href={go('admin.payments.transactions.index')} key={x.id} className="flex justify-between p-4 text-sm hover:bg-slate-50"><span><b>{x.transaction_id}</b><small className="block text-slate-500">{x.gateway} · {x.date}</small></span><span className="text-right"><b>{money(x.amount)}</b><small className={`block font-bold ${x.status==='Completed'?'text-emerald-700':x.status==='Failed'?'text-rose-700':'text-amber-700'}`}>{x.status}</small></span></Link>)}</div></Panel>
  </div>
  <Panel title="Recent collections" action={<Link href={go('admin.fees.payments')} className="text-xs font-bold text-indigo-700">All payments →</Link>}><div className="overflow-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Student</th><th>Date</th><th>Method</th><th className="text-right">Amount</th></tr></thead><tbody>{finance.recentPayments.map(x=><tr key={x.id} className="border-t"><td className="p-3"><b>{x.student}</b><small className="block text-slate-500">{x.admission_no}</small></td><td>{x.date}</td><td>{x.method}</td><td className="pr-3 text-right font-bold text-emerald-700">{money(x.amount)}</td></tr>)}</tbody></table></div></Panel>
 </main></AuthenticatedLayout>;
}
