import { Head, Link, useForm } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';

export default function StaffServices({ staff, leaveTypes, leaves, payrolls, shifts, documents }) {
  const {data,setData,post,processing,errors,reset}=useForm({leave_type_id:'',start_date:'',end_date:'',reason:''});
  const submit=e=>{e.preventDefault();post(route('portal.staff.leave'),{onSuccess:()=>reset()});};
  return <AuthenticatedLayout><Head title="My HR & Payroll"/><div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-8">
    <div><Link href={route('dashboard')} className="text-sm font-bold text-indigo-600">← Dashboard</Link><h1 className="mt-2 text-3xl font-black text-slate-900">My HR &amp; Payroll</h1><p className="text-slate-500">{staff.first_name} {staff.last_name} · {staff.designation?.name}</p></div>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Apply for leave</h2><form onSubmit={submit} className="mt-4 grid gap-3"><select value={data.leave_type_id} onChange={e=>setData('leave_type_id',e.target.value)} required className="rounded-xl border-slate-300"><option value="">Leave type</option>{leaveTypes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><input type="date" value={data.start_date} onChange={e=>setData('start_date',e.target.value)} required className="rounded-xl border-slate-300"/><input type="date" value={data.end_date} onChange={e=>setData('end_date',e.target.value)} required className="rounded-xl border-slate-300"/></div><textarea value={data.reason} onChange={e=>setData('reason',e.target.value)} placeholder="Reason" required className="rounded-xl border-slate-300"/>{Object.values(errors).map((x,i)=><p key={i} className="text-xs text-red-600">{x}</p>)}<button disabled={processing} className="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white">Submit request</button></form></section>
      <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Recent leave requests</h2><div className="mt-3 divide-y">{leaves.map(x=><div key={x.id} className="flex justify-between py-3 text-sm"><span>{x.leave_type?.name} · {x.start_date}–{x.end_date}</span><b className="capitalize">{x.status}</b></div>)}</div></section></div>
    <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Payslips</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>Month</th><th>Basic</th><th>Allowance</th><th>Deduction</th><th>Net</th><th>Status</th></tr></thead><tbody>{payrolls.map(x=><tr key={x.id} className="border-t"><td className="py-3">{x.salary_month}</td><td>{x.basic_salary}</td><td>{x.allowance}</td><td>{x.deduction}</td><td className="font-bold">{x.net_salary}</td><td className="capitalize">{x.status}</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Upcoming shifts</h2>{shifts.map(x=><p key={x.id} className="border-b py-3 text-sm">{x.shift_date} · {x.starts_at}–{x.ends_at} · {x.location||'Campus'}</p>)}</section><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">My documents</h2>{documents.map(x=><a key={x.id} href={`/storage/${x.file_path}`} className="block border-b py-3 text-sm font-semibold text-indigo-600">{x.title}</a>)}</section></div>
  </div></AuthenticatedLayout>;
}
