import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { useState } from 'react';

const badge = value => `rounded-full border px-2.5 py-1 text-xs font-bold ${['Paid','Approved','Returned','Completed','Passed','Evaluated'].includes(value)?'border-emerald-200 bg-emerald-50 text-emerald-700':['Rejected','Failed','Overdue','Lost'].includes(value)?'border-rose-200 bg-rose-50 text-rose-700':'border-amber-200 bg-amber-50 text-amber-700'}`;
const money = value => `৳ ${Number(value||0).toLocaleString()}`;
function Card({title, children}) { return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><h2 className="border-b p-4 text-base font-bold text-slate-900">{title}</h2><div className="p-4">{children}</div></section>; }
function FieldError({error}) { return error && <p className="mt-1 text-xs text-rose-600">{error}</p>; }

function HomeworkForm({item}) {
 const form=useForm({answer:'',attachment:null});
 return <div className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="text-xs font-bold text-emerald-700">{item.subject}</p><h3 className="font-bold">{item.title}</h3><p className="mt-1 text-xs text-slate-500">Due: {item.due} · Marks: {item.total_marks}</p></div>{item.submission&&<span className={badge(item.submission.status)}>{item.submission.status}</span>}</div>{item.description&&<p className="mt-3 text-sm text-slate-600">{item.description}</p>}
 <form onSubmit={e=>{e.preventDefault();form.post(route('portal.homework.submit',item.id),{forceFormData:true,preserveScroll:true})}} className="mt-3 space-y-2"><textarea value={form.data.answer} onChange={e=>form.setData('answer',e.target.value)} placeholder="Write your answer" className="w-full rounded-lg border-slate-300 text-sm"/><input type="file" onChange={e=>form.setData('attachment',e.target.files[0])} className="block w-full text-xs"/><FieldError error={form.errors.answer}/><button disabled={form.processing} className="rounded-lg bg-emerald-800 px-3 py-2 text-xs font-bold text-white">{item.submission?'Resubmit':'Submit Homework'}</button>{item.submission?.teacher_feedback&&<p className="rounded-lg bg-blue-50 p-2 text-xs text-blue-800">Teacher: {item.submission.teacher_feedback} {item.submission.marks_obtained!==null&&`· Marks ${item.submission.marks_obtained}`}</p>}</form></div>;
}

export default function StudentServices(props) {
 const [tab,setTab]=useState('tasks');
 const leave=useForm({leave_type:'Sick Leave',start_date:'',end_date:'',reason:'',attachment:null});
 const correction=useForm({attendance_date:'',requested_status:'present',reason:''});
 const profile=useForm({phone:'',email:'',present_address:'',permanent_address:'',reason:''});
 const ticket=useForm({subject:'',description:'',priority:'Medium'});
 const tabs=[['tasks','Tasks & Homework'],['attendance','Attendance & Leave'],['fees','Fees'],['exams','Online Exams'],['library','Library'],['campus','Transport & Hostel'],['support','Support & Profile']];
 return <AuthenticatedLayout><Head title="Student Services"/><main className="space-y-5 py-4 sm:px-2 sm:py-6">
  <div className="rounded-3xl bg-gradient-to-br from-emerald-950 to-emerald-800 p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-amber-300">Student Self-Service</p><h1 className="mt-2 text-2xl font-bold">My School Account</h1><p className="mt-1 text-sm text-emerald-100">Homework, attendance, fees, exam, library এবং requests এক জায়গায়</p></div>
  <div className="flex gap-2 overflow-x-auto rounded-xl border bg-white p-2">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold ${tab===id?'bg-emerald-800 text-white':'text-slate-600 hover:bg-slate-100'}`}>{label}</button>)}</div>
  {tab==='tasks'&&<Card title="Homework & Assignment">{props.homework.length?<div className="grid gap-3 lg:grid-cols-2">{props.homework.map(x=><HomeworkForm key={x.id} item={x}/>)}</div>:<p className="text-sm text-slate-500">No homework assigned.</p>}</Card>}
  {tab==='attendance'&&<div className="grid gap-5 lg:grid-cols-2"><Card title="Recent Attendance"><div className="flex flex-wrap gap-2">{props.attendance.map((x,i)=><div key={i} className="rounded-lg border p-2 text-center"><p className="text-xs">{x.attendance_date}</p><span className={badge(x.status)}>{x.status}</span></div>)}</div><form onSubmit={e=>{e.preventDefault();correction.post(route('portal.attendance-correction.store'),{preserveScroll:true})}} className="mt-5 grid gap-2"><h3 className="font-bold">Correction Request</h3><input type="date" value={correction.data.attendance_date} onChange={e=>correction.setData('attendance_date',e.target.value)} className="rounded-lg border-slate-300"/><select value={correction.data.requested_status} onChange={e=>correction.setData('requested_status',e.target.value)} className="rounded-lg border-slate-300"><option value="present">Present</option><option value="late">Late</option><option value="leave">Leave</option></select><textarea placeholder="Reason" value={correction.data.reason} onChange={e=>correction.setData('reason',e.target.value)} className="rounded-lg border-slate-300"/><FieldError error={correction.errors.attendance_date||correction.errors.reason}/><button className="rounded-lg bg-emerald-800 p-2 text-sm font-bold text-white">Request Correction</button></form></Card>
  <Card title="Leave Application"><form onSubmit={e=>{e.preventDefault();leave.post(route('portal.leave.store'),{forceFormData:true,preserveScroll:true})}} className="grid gap-2"><input placeholder="Leave type" value={leave.data.leave_type} onChange={e=>leave.setData('leave_type',e.target.value)} className="rounded-lg border-slate-300"/><div className="grid grid-cols-2 gap-2"><input type="date" value={leave.data.start_date} onChange={e=>leave.setData('start_date',e.target.value)} className="rounded-lg border-slate-300"/><input type="date" value={leave.data.end_date} onChange={e=>leave.setData('end_date',e.target.value)} className="rounded-lg border-slate-300"/></div><textarea placeholder="Reason" value={leave.data.reason} onChange={e=>leave.setData('reason',e.target.value)} className="rounded-lg border-slate-300"/><input type="file" onChange={e=>leave.setData('attachment',e.target.files[0])}/><FieldError error={leave.errors.start_date||leave.errors.reason}/><button className="rounded-lg bg-emerald-800 p-2 text-sm font-bold text-white">Apply</button></form><div className="mt-4 space-y-2">{props.leaves.map(x=><div key={x.id} className="flex justify-between rounded-lg border p-3 text-sm"><span>{x.leave_type}: {x.start_date}–{x.end_date}</span><span className={badge(x.school_status)}>{x.school_status}</span></div>)}</div></Card></div>}
  {tab==='fees'&&<Card title="Invoices & Payment History"><div className="space-y-2">{props.invoices.map(x=>{const due=Number(x.amount)+Number(x.fine)-Number(x.discount)-Number(x.paid_amount);return <div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-bold">{x.invoice_no} · {x.fee_group?.name}</p><p className="text-xs text-slate-500">Due {x.due_date} · {x.status}</p></div><div className="flex items-center gap-2"><strong>{money(due)}</strong>{due>0&&<button onClick={()=>{const amount=prompt('Payment amount',due);if(amount)router.post(route('portal.payment.request',x.id),{amount,payment_method:'Online'})}} className="rounded-lg bg-emerald-800 px-3 py-2 text-xs font-bold text-white">Pay / Request</button>}</div></div>})}</div><h3 className="mt-5 font-bold">Transactions</h3><div className="mt-2 space-y-2">{props.transactions.map(x=><div key={x.id} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{x.transaction_id} · {x.payment_method}</span><span>{money(x.amount)} · {x.status}</span></div>)}</div></Card>}
  {tab==='exams'&&<Card title="Available Online Exams"><div className="grid gap-3 sm:grid-cols-2">{props.onlineExams.map(x=><div key={x.id} className="rounded-xl border p-4"><h3 className="font-bold">{x.title}</h3><p className="mt-1 text-xs text-slate-500">{x.subject?.name} · {x.exam_date} · {x.duration_minutes} min</p><Link href={route('portal.exams.start',x.id)} className="mt-3 inline-flex rounded-lg bg-emerald-800 px-3 py-2 text-xs font-bold text-white">Start / Continue</Link></div>)}</div></Card>}
  {tab==='library'&&<div className="grid gap-5 lg:grid-cols-2"><Card title="My Issued Books">{props.books.map(x=><div key={x.id} className="mb-2 flex justify-between rounded-lg border p-3 text-sm"><span>{x.book?.title}<small className="block text-slate-500">Due {x.due_date}</small></span><span className={badge(x.status)}>{x.status} · Fine {money(x.fine_amount)}</span></div>)}</Card><Card title="Reserve a Book"><div className="space-y-2">{props.availableBooks.map(x=><div key={x.id} className="flex justify-between rounded-lg border p-3 text-sm"><span><strong>{x.title}</strong><small className="block text-slate-500">{x.author}</small></span><button onClick={()=>router.post(route('portal.library-reservation.store'),{book_id:x.id})} className="rounded-lg bg-emerald-800 px-3 text-xs font-bold text-white">Reserve</button></div>)}</div></Card></div>}
  {tab==='campus'&&<div className="grid gap-5 lg:grid-cols-2"><Card title="My Transport">{props.transport?<div className="space-y-2 text-sm"><p><b>Vehicle:</b> {props.transport.vehicle?.vehicle_number}</p><p><b>Route:</b> {props.transport.vehicle?.route_name}</p><p><b>Pickup:</b> {props.transport.pickup_point}</p><p><b>Driver:</b> {props.transport.vehicle?.driver_name} · {props.transport.vehicle?.driver_phone}</p></div>:<p className="text-sm text-slate-500">No transport assigned.</p>}</Card><Card title="My Hostel">{props.hostel?<div className="space-y-2 text-sm"><p><b>Hostel:</b> {props.hostel.room?.hostel_name}</p><p><b>Room:</b> {props.hostel.room?.room_number}</p><p><b>Type:</b> {props.hostel.room?.room_type}</p><p><b>Monthly fee:</b> {money(props.hostel.monthly_fee)}</p></div>:<p className="text-sm text-slate-500">No hostel assigned.</p>}</Card></div>}
  {tab==='support'&&<div className="grid gap-5 lg:grid-cols-2"><Card title="Helpdesk / Complaint"><form onSubmit={e=>{e.preventDefault();ticket.post(route('portal.ticket.store'),{preserveScroll:true})}} className="grid gap-2"><input placeholder="Subject" value={ticket.data.subject} onChange={e=>ticket.setData('subject',e.target.value)} className="rounded-lg border-slate-300"/><select value={ticket.data.priority} onChange={e=>ticket.setData('priority',e.target.value)} className="rounded-lg border-slate-300"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select><textarea placeholder="Describe your issue" value={ticket.data.description} onChange={e=>ticket.setData('description',e.target.value)} className="rounded-lg border-slate-300"/><button className="rounded-lg bg-emerald-800 p-2 text-sm font-bold text-white">Submit Ticket</button></form><div className="mt-4 space-y-2">{props.tickets.map(x=><div key={x.id} className="flex justify-between rounded-lg border p-3 text-sm"><span>{x.ticket_number} · {x.subject}</span><span className={badge(x.status)}>{x.status}</span></div>)}</div></Card><Card title="Profile Update Request"><form onSubmit={e=>{e.preventDefault();profile.post(route('portal.profile-update.store'),{preserveScroll:true})}} className="grid gap-2"><input placeholder="New phone" value={profile.data.phone} onChange={e=>profile.setData('phone',e.target.value)} className="rounded-lg border-slate-300"/><input type="email" placeholder="New email" value={profile.data.email} onChange={e=>profile.setData('email',e.target.value)} className="rounded-lg border-slate-300"/><textarea placeholder="New present address" value={profile.data.present_address} onChange={e=>profile.setData('present_address',e.target.value)} className="rounded-lg border-slate-300"/><textarea placeholder="Reason" value={profile.data.reason} onChange={e=>profile.setData('reason',e.target.value)} className="rounded-lg border-slate-300"/><FieldError error={profile.errors.phone}/><button className="rounded-lg bg-emerald-800 p-2 text-sm font-bold text-white">Request Update</button></form></Card></div>}
 </main></AuthenticatedLayout>;
}
