[program:erp-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/erp/artisan queue:work --queue=default,communications,reports,backups --sleep=3 --tries=4 --timeout=1800 --max-time=3600
directory=/var/www/erp
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/erp-worker.log
stopwaitsecs=1810
