import { Head, router, useForm } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';

const Field=({label,children})=><label className="block text-sm font-medium text-slate-700">{label}{children}</label>;
const Input=props=><input {...props} className="mt-1 w-full rounded-lg border-slate-300 text-sm focus:border-indigo-500 focus:ring-indigo-500"/>;
const Select=({children,...props})=><select {...props} className="mt-1 w-full rounded-lg border-slate-300 text-sm focus:border-indigo-500 focus:ring-indigo-500">{children}</select>;
const Card=({title,children})=><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-bold text-slate-900">{title}</h2>{children}</section>;
const Button=({children})=><button className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700">{children}</button>;

export default function Index({assignments,topics,diaries,substitutions,meetings,transfers,sessions,classes,subjects,staff,students}){
 const a=useForm({staff_id:'',class_id:'',section_id:'',subject_id:'',is_class_teacher:false});
 const t=useForm({academic_session_id:'',class_id:'',section_id:'',subject_id:'',title:'',planned_date:''});
 const d=useForm({date:new Date().toISOString().slice(0,10),class_id:'',section_id:'',subject_id:'',teacher_id:'',topic:'',homework:'',notes:''});
 const s=useForm({date:new Date().toISOString().slice(0,10),class_id:'',section_id:'',subject_id:'',absent_teacher_id:'',substitute_teacher_id:'',start_time:'',end_time:'',reason:''});
 const m=useForm({student_id:'',teacher_id:'',scheduled_at:'',agenda:'',notes:''});
 const x=useForm({student_id:'',type:'transfer',effective_date:new Date().toISOString().slice(0,10),reason:'',destination_school:''});
 const opts=(items,label)=><>{<option value="">Select</option>}{items.map(i=><option key={i.id} value={i.id}>{label(i)}</option>)}</>;
 const sections=(classId)=>classes.find(c=>String(c.id)===String(classId))?.sections||[];
 const submit=(form,url)=>e=>{e.preventDefault();form.post(route(url),{preserveScroll:true,onSuccess:()=>form.reset()});};
 const Summary=({rows,render})=><div className="mt-4 max-h-48 overflow-auto divide-y text-sm">{rows.length?rows.map(render):<p className="py-3 text-slate-500">No records yet.</p>}</div>;
 return <AuthenticatedLayout><Head title="Academic Operations"/><div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6">
  <div><h1 className="text-2xl font-bold text-slate-900">Academic Operations</h1><p className="text-sm text-slate-500">Teacher allocation, syllabus, class diary, substitutions, meetings and student transfer.</p></div>
  <div className="grid gap-6 xl:grid-cols-2">
   <Card title="Teacher Assignment"><form onSubmit={submit(a,'admin.academic-operations.assignment')} className="grid grid-cols-2 gap-3">
    <Field label="Teacher"><Select value={a.data.staff_id} onChange={e=>a.setData('staff_id',e.target.value)} required>{opts(staff,i=>`${i.first_name} ${i.last_name||''}`)}</Select></Field>
    <Field label="Class"><Select value={a.data.class_id} onChange={e=>a.setData('class_id',e.target.value)} required>{opts(classes,i=>i.name)}</Select></Field>
    <Field label="Section"><Select value={a.data.section_id} onChange={e=>a.setData('section_id',e.target.value)} required>{opts(sections(a.data.class_id),i=>i.name)}</Select></Field>
    <Field label="Subject"><Select value={a.data.subject_id} onChange={e=>a.setData('subject_id',e.target.value)} required>{opts(subjects,i=>i.name)}</Select></Field>
    <label className="col-span-2 flex gap-2 text-sm"><input type="checkbox" checked={a.data.is_class_teacher} onChange={e=>a.setData('is_class_teacher',e.target.checked)}/> Class teacher</label><Button>Save assignment</Button>
   </form><Summary rows={assignments} render={r=><div key={r.id} className="py-2">{r.staff?.first_name} — {r.school_class?.name} / {r.section?.name} / {r.subject?.name}</div>}/></Card>

   <Card title="Syllabus Progress"><form onSubmit={submit(t,'admin.academic-operations.topic')} className="grid grid-cols-2 gap-3">
    <Field label="Session"><Select value={t.data.academic_session_id} onChange={e=>t.setData('academic_session_id',e.target.value)} required>{opts(sessions,i=>i.name)}</Select></Field><Field label="Class"><Select value={t.data.class_id} onChange={e=>t.setData('class_id',e.target.value)} required>{opts(classes,i=>i.name)}</Select></Field>
    <Field label="Section (optional)"><Select value={t.data.section_id} onChange={e=>t.setData('section_id',e.target.value)}>{opts(sections(t.data.class_id),i=>i.name)}</Select></Field><Field label="Subject"><Select value={t.data.subject_id} onChange={e=>t.setData('subject_id',e.target.value)} required>{opts(subjects,i=>i.name)}</Select></Field>
    <Field label="Topic"><Input value={t.data.title} onChange={e=>t.setData('title',e.target.value)} required/></Field><Field label="Planned date"><Input type="date" value={t.data.planned_date} onChange={e=>t.setData('planned_date',e.target.value)}/></Field><Button>Add topic</Button>
   </form><Summary rows={topics} render={r=><div key={r.id} className="flex items-center justify-between py-2"><span>{r.title} <b className="text-indigo-600">{r.status}</b></span><button onClick={()=>router.patch(route('admin.academic-operations.topic-status',r.id),{status:r.status==='planned'?'in_progress':'completed'})} className="text-indigo-600">Advance</button></div>}/></Card>

   <Card title="Class Diary"><form onSubmit={submit(d,'admin.academic-operations.diary')} className="grid grid-cols-2 gap-3">
    <Field label="Date"><Input type="date" value={d.data.date} onChange={e=>d.setData('date',e.target.value)} required/></Field><Field label="Teacher"><Select value={d.data.teacher_id} onChange={e=>d.setData('teacher_id',e.target.value)} required>{opts(staff,i=>i.first_name)}</Select></Field>
    <Field label="Class"><Select value={d.data.class_id} onChange={e=>d.setData('class_id',e.target.value)} required>{opts(classes,i=>i.name)}</Select></Field><Field label="Section"><Select value={d.data.section_id} onChange={e=>d.setData('section_id',e.target.value)} required>{opts(sections(d.data.class_id),i=>i.name)}</Select></Field>
    <Field label="Subject"><Select value={d.data.subject_id} onChange={e=>d.setData('subject_id',e.target.value)}>{opts(subjects,i=>i.name)}</Select></Field><Field label="Topic taught"><Input value={d.data.topic} onChange={e=>d.setData('topic',e.target.value)} required/></Field><Field label="Homework"><Input value={d.data.homework} onChange={e=>d.setData('homework',e.target.value)}/></Field><div><Button>Save diary</Button></div>
   </form><Summary rows={diaries} render={r=><div key={r.id} className="py-2">{r.date} — {r.topic}{r.homework&&` · Homework: ${r.homework}`}</div>}/></Card>

   <Card title="Substitute Class"><form onSubmit={submit(s,'admin.academic-operations.substitution')} className="grid grid-cols-2 gap-3">
    <Field label="Date"><Input type="date" value={s.data.date} onChange={e=>s.setData('date',e.target.value)} required/></Field><Field label="Class"><Select value={s.data.class_id} onChange={e=>s.setData('class_id',e.target.value)} required>{opts(classes,i=>i.name)}</Select></Field><Field label="Section"><Select value={s.data.section_id} onChange={e=>s.setData('section_id',e.target.value)} required>{opts(sections(s.data.class_id),i=>i.name)}</Select></Field><Field label="Subject"><Select value={s.data.subject_id} onChange={e=>s.setData('subject_id',e.target.value)}>{opts(subjects,i=>i.name)}</Select></Field>
    <Field label="Absent teacher"><Select value={s.data.absent_teacher_id} onChange={e=>s.setData('absent_teacher_id',e.target.value)} required>{opts(staff,i=>i.first_name)}</Select></Field><Field label="Substitute teacher"><Select value={s.data.substitute_teacher_id} onChange={e=>s.setData('substitute_teacher_id',e.target.value)} required>{opts(staff,i=>i.first_name)}</Select></Field><Field label="Start"><Input type="time" value={s.data.start_time} onChange={e=>s.setData('start_time',e.target.value)}/></Field><Field label="End"><Input type="time" value={s.data.end_time} onChange={e=>s.setData('end_time',e.target.value)}/></Field><div><Button>Assign</Button></div>
   </form><Summary rows={substitutions} render={r=><div key={r.id} className="py-2">{r.date} · Teacher #{r.absent_teacher_id} → #{r.substitute_teacher_id}</div>}/></Card>

   <Card title="Parent–Teacher Meeting"><form onSubmit={submit(m,'admin.academic-operations.meeting')} className="grid grid-cols-2 gap-3"><Field label="Student"><Select value={m.data.student_id} onChange={e=>m.setData('student_id',e.target.value)} required>{opts(students,i=>`${i.admission_no} — ${i.first_name}`)}</Select></Field><Field label="Teacher"><Select value={m.data.teacher_id} onChange={e=>m.setData('teacher_id',e.target.value)} required>{opts(staff,i=>i.first_name)}</Select></Field><Field label="Schedule"><Input type="datetime-local" value={m.data.scheduled_at} onChange={e=>m.setData('scheduled_at',e.target.value)} required/></Field><Field label="Agenda"><Input value={m.data.agenda} onChange={e=>m.setData('agenda',e.target.value)} required/></Field><div><Button>Schedule</Button></div></form><Summary rows={meetings} render={r=><div key={r.id} className="flex justify-between py-2"><span>{r.requested_at} · {r.agenda}</span><button className="text-emerald-600" onClick={()=>router.patch(route('admin.academic-operations.meeting-status',r.id),{status:'completed'})}>Complete</button></div>}/></Card>

   <Card title="Transfer / Withdrawal"><form onSubmit={submit(x,'admin.academic-operations.transfer')} className="grid grid-cols-2 gap-3"><Field label="Student"><Select value={x.data.student_id} onChange={e=>x.setData('student_id',e.target.value)} required>{opts(students,i=>`${i.admission_no} — ${i.first_name}`)}</Select></Field><Field label="Type"><Select value={x.data.type} onChange={e=>x.setData('type',e.target.value)}><option value="transfer">Transfer</option><option value="withdrawal">Withdrawal</option></Select></Field><Field label="Effective date"><Input type="date" value={x.data.effective_date} onChange={e=>x.setData('effective_date',e.target.value)} required/></Field><Field label="Destination school"><Input value={x.data.destination_school} onChange={e=>x.setData('destination_school',e.target.value)}/></Field><Field label="Reason"><Input value={x.data.reason} onChange={e=>x.setData('reason',e.target.value)} required/></Field><div><Button>Create request</Button></div></form><Summary rows={transfers} render={r=><div key={r.id} className="flex justify-between py-2"><span>{r.type} · Student #{r.student_id} · {r.status} {r.certificate_no&&`· ${r.certificate_no}`}</span>{r.status==='requested'&&<button className="text-emerald-600" onClick={()=>router.patch(route('admin.academic-operations.transfer-approve',r.id))}>Approve</button>}</div>}/></Card>
  </div>
 </div></AuthenticatedLayout>;
}
