import {Head,router,useForm} from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
const input='mt-1 w-full rounded-xl border-slate-300 text-sm focus:border-indigo-500 focus:ring-indigo-500';
export default function Index({policy,locks,classes,holidays}){
 const p=useForm({student_start_time:policy?.student_start_time?.slice(0,5)||'08:00',staff_start_time:policy?.staff_start_time?.slice(0,5)||'08:00',late_grace_minutes:policy?.late_grace_minutes||15,half_day_after_minutes:policy?.half_day_after_minutes||180,weekly_holidays:policy?.weekly_holidays||[5],block_holiday_entry:policy?.block_holiday_entry??true,auto_absent_sms:policy?.auto_absent_sms??false});
 const l=useForm({attendance_type:'student',attendance_date:new Date().toISOString().slice(0,10),class_id:'',section_id:''});
 const sections=classes.find(c=>String(c.id)===String(l.data.class_id))?.sections||[];
 return <AuthenticatedLayout><Head title="Attendance Control"/><div className="mx-auto max-w-6xl space-y-6 p-6"><div><h1 className="text-2xl font-bold text-slate-900">Attendance Control & Policy</h1><p className="text-sm text-slate-500">Manual, biometric, holiday and approved-leave attendance rules in one place.</p></div><div className="grid gap-6 lg:grid-cols-2">
 <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="mb-4 font-bold">Automatic Attendance Rules</h2><form onSubmit={e=>{e.preventDefault();p.post(route('admin.attendance-control.policy'))}} className="grid grid-cols-2 gap-4">
 {[['Student start','student_start_time','time'],['Staff start','staff_start_time','time'],['Late grace (minutes)','late_grace_minutes','number'],['Half-day after (minutes)','half_day_after_minutes','number']].map(([a,b,c])=><label key={b} className="text-sm font-medium">{a}<input className={input} type={c} value={p.data[b]} onChange={e=>p.setData(b,e.target.value)}/></label>)}
 <div className="col-span-2"><p className="mb-2 text-sm font-medium">Weekly holidays</p><div className="flex flex-wrap gap-3">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,i)=><label key={day} className="text-sm"><input type="checkbox" className="mr-1 rounded" checked={p.data.weekly_holidays.includes(i)} onChange={e=>p.setData('weekly_holidays',e.target.checked?[...p.data.weekly_holidays,i]:p.data.weekly_holidays.filter(x=>x!==i))}/>{day}</label>)}</div></div>
 <label className="col-span-2 text-sm"><input type="checkbox" className="mr-2 rounded" checked={p.data.block_holiday_entry} onChange={e=>p.setData('block_holiday_entry',e.target.checked)}/>Block entry on holidays</label><label className="col-span-2 text-sm"><input type="checkbox" className="mr-2 rounded" checked={p.data.auto_absent_sms} onChange={e=>p.setData('auto_absent_sms',e.target.checked)}/>Enable automatic absent SMS</label><button className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">Save policy</button></form></section>
 <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="mb-4 font-bold">Close Attendance Day</h2><form onSubmit={e=>{e.preventDefault();l.post(route('admin.attendance-control.lock'))}} className="grid grid-cols-2 gap-4"><label className="text-sm">Type<select className={input} value={l.data.attendance_type} onChange={e=>l.setData('attendance_type',e.target.value)}><option value="student">Student</option><option value="staff">Staff</option></select></label><label className="text-sm">Date<input className={input} type="date" value={l.data.attendance_date} onChange={e=>l.setData('attendance_date',e.target.value)}/></label>{l.data.attendance_type==='student'&&<><label className="text-sm">Class<select className={input} value={l.data.class_id} onChange={e=>l.setData('class_id',e.target.value)}><option value="">Select</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm">Section<select className={input} value={l.data.section_id} onChange={e=>l.setData('section_id',e.target.value)}><option value="">All</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></>}<button className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">Lock day</button></form><div className="mt-5 divide-y">{locks.map(r=><div key={r.id} className="flex justify-between py-2 text-sm"><span>{r.attendance_date} · {r.attendance_type}</span><button onClick={()=>router.delete(route('admin.attendance-control.unlock',r.id))} className="font-semibold text-rose-600">Reopen</button></div>)}</div></section>
 </div><section className="rounded-2xl border bg-white p-6"><h2 className="mb-3 font-bold">Government / Academic Holidays</h2>{holidays.length?holidays.map(h=><div key={h.id} className="border-b py-2 text-sm">{h.title} — {h.start_datetime}</div>):<p className="text-sm text-slate-500">No configured holidays.</p>}</section></div></AuthenticatedLayout>;
}
