<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::table('users',function(Blueprint $t){$t->boolean('two_factor_enabled')->default(false);$t->string('two_factor_channel')->default('email');$t->timestamp('password_changed_at')->nullable();$t->unsignedSmallInteger('password_expires_days')->nullable();$t->timestamp('locked_until')->nullable();});
 Schema::table('saas_backups',function(Blueprint $t){$t->string('disk')->default('local');$t->string('path')->nullable();$t->string('checksum',64)->nullable();$t->boolean('encrypted')->default(true);$t->text('error_message')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamp('verified_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();});
 Schema::create('security_policies',function(Blueprint $t){$t->id();$t->string('key')->unique();$t->text('value')->nullable();$t->timestamps();});
 Schema::create('system_error_events',function(Blueprint $t){$t->id();$t->string('level');$t->string('fingerprint',64)->index();$t->text('message');$t->text('location')->nullable();$t->json('context')->nullable();$t->timestamp('occurred_at');$t->timestamp('resolved_at')->nullable();$t->foreignId('resolved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('system_health_checks',function(Blueprint $t){$t->id();$t->string('component');$t->string('status');$t->unsignedInteger('response_ms')->nullable();$t->text('message')->nullable();$t->timestamp('checked_at');$t->timestamps();});
 Schema::create('data_retention_runs',function(Blueprint $t){$t->id();$t->string('scope');$t->unsignedInteger('retention_days');$t->unsignedInteger('records_deleted')->default(0);$t->string('status');$t->text('details')->nullable();$t->foreignId('executed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('executed_at');$t->timestamps();});
 Schema::create('disaster_recovery_tests',function(Blueprint $t){$t->id();$t->foreignId('saas_backup_id')->nullable()->constrained()->nullOnDelete();$t->string('status');$t->string('checksum_status')->nullable();$t->text('details')->nullable();$t->timestamp('tested_at');$t->foreignId('tested_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
}public function down():void{foreach(['disaster_recovery_tests','data_retention_runs','system_health_checks','system_error_events','security_policies']as$x)Schema::dropIfExists($x);Schema::table('saas_backups',function(Blueprint$t){$t->dropConstrainedForeignId('created_by');$t->dropColumn(['disk','path','checksum','encrypted','error_message','completed_at','verified_at']);});Schema::table('users',fn(Blueprint$t)=>$t->dropColumn(['two_factor_enabled','two_factor_channel','password_changed_at','password_expires_days','locked_until']));}};
