<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::table('health_records',function(Blueprint $t){$t->boolean('emergency_alert')->default(false);$t->text('emergency_instructions')->nullable();$t->string('data_classification')->default('restricted');$t->foreignId('last_updated_by')->nullable()->constrained('users')->nullOnDelete();});
 Schema::table('medicine_stocks',function(Blueprint $t){$t->unsignedInteger('reorder_level')->default(10);});
 Schema::table('vaccinations',function(Blueprint $t){$t->timestamp('reminder_sent_at')->nullable();});
 Schema::create('medical_consents',function(Blueprint $t){$t->id();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->foreignId('guardian_id')->nullable()->constrained()->nullOnDelete();$t->string('consent_type');$t->boolean('is_granted');$t->date('valid_from');$t->date('valid_until')->nullable();$t->text('restrictions')->nullable();$t->string('signed_name');$t->timestamp('signed_at');$t->foreignId('recorded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('medicine_issues',function(Blueprint $t){$t->id();$t->foreignId('medicine_stock_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->unsignedInteger('quantity');$t->string('dosage')->nullable();$t->string('prescribed_by')->nullable();$t->text('reason')->nullable();$t->timestamp('issued_at');$t->foreignId('issued_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('doctor_appointments',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('doctor_name');$t->dateTime('scheduled_at');$t->string('location')->nullable();$t->string('status')->default('scheduled');$t->text('reason')->nullable();$t->text('outcome')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('medical_emergency_alerts',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('severity');$t->text('message');$t->string('location')->nullable();$t->timestamp('occurred_at');$t->boolean('guardian_notified')->default(false);$t->timestamp('acknowledged_at')->nullable();$t->foreignId('reported_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('medical_documents',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('title');$t->string('document_type');$t->string('file_path');$t->string('visibility')->default('medical_only');$t->date('document_date')->nullable();$t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
}public function down():void{Schema::dropIfExists('medical_documents');Schema::dropIfExists('medical_emergency_alerts');Schema::dropIfExists('doctor_appointments');Schema::dropIfExists('medicine_issues');Schema::dropIfExists('medical_consents');Schema::table('vaccinations',fn(Blueprint $t)=>$t->dropColumn('reminder_sent_at'));Schema::table('medicine_stocks',fn(Blueprint $t)=>$t->dropColumn('reorder_level'));Schema::table('health_records',function(Blueprint $t){$t->dropConstrainedForeignId('last_updated_by');$t->dropColumn(['emergency_alert','emergency_instructions','data_classification']);});}};
