<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 if(!Schema::hasColumn('vehicles','transport_route_id'))Schema::table('vehicles',function(Blueprint $t){$t->foreignId('transport_route_id')->nullable()->constrained()->nullOnDelete();$t->string('tracking_token_hash',64)->nullable()->unique();$t->date('insurance_expires_at')->nullable();$t->date('fitness_expires_at')->nullable();$t->date('registration_expires_at')->nullable();});
 if(!Schema::hasTable('transport_personnel'))Schema::create('transport_personnel',function(Blueprint $t){$t->id();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->string('type');$t->string('name');$t->string('phone');$t->string('license_no')->nullable();$t->date('license_expires_at')->nullable();$t->string('national_id')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
 if(!Schema::hasTable('transport_vehicle_personnel'))Schema::create('transport_vehicle_personnel',function(Blueprint $t){$t->id();$t->foreignId('vehicle_id')->constrained()->cascadeOnDelete();$t->foreignId('transport_personnel_id')->constrained('transport_personnel')->cascadeOnDelete();$t->date('assigned_from');$t->date('assigned_until')->nullable();$t->timestamps();});
 if(!Schema::hasTable('transport_stops'))Schema::create('transport_stops',function(Blueprint $t){$t->id();$t->foreignId('transport_route_id')->constrained()->cascadeOnDelete();$t->string('name');$t->unsignedSmallInteger('sequence');$t->time('pickup_time')->nullable();$t->time('drop_time')->nullable();$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->unsignedInteger('geofence_radius_m')->default(200);$t->decimal('monthly_fare',10,2)->default(0);$t->timestamps();$t->unique(['transport_route_id','sequence']);});
 if(!Schema::hasTable('vehicle_fuel_logs'))Schema::create('vehicle_fuel_logs',function(Blueprint $t){$t->id();$t->foreignId('vehicle_id')->constrained()->cascadeOnDelete();$t->date('date');$t->decimal('litres',10,2);$t->decimal('unit_price',10,2);$t->decimal('odometer',12,2)->nullable();$t->string('vendor')->nullable();$t->string('receipt_no')->nullable();$t->foreignId('recorded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 if(!Schema::hasTable('vehicle_maintenance_logs'))Schema::create('vehicle_maintenance_logs',function(Blueprint $t){$t->id();$t->foreignId('vehicle_id')->constrained()->cascadeOnDelete();$t->string('type');$t->date('service_date')->nullable();$t->date('next_due_date')->nullable();$t->decimal('next_due_odometer',12,2)->nullable();$t->decimal('cost',12,2)->default(0);$t->string('vendor')->nullable();$t->string('status')->default('scheduled');$t->text('notes')->nullable();$t->timestamps();});
 if(!Schema::hasTable('transport_personnel_documents'))Schema::create('transport_personnel_documents',function(Blueprint $t){$t->id();$t->foreignId('transport_personnel_id')->constrained('transport_personnel')->cascadeOnDelete();$t->string('type');$t->string('number')->nullable();$t->date('expires_at')->nullable();$t->string('file_path')->nullable();$t->timestamps();});
 if(!Schema::hasTable('student_boarding_attendances'))Schema::create('student_boarding_attendances',function(Blueprint $t){$t->id();$t->foreignId('transport_allocation_id')->constrained()->cascadeOnDelete();$t->foreignId('vehicle_id')->constrained()->cascadeOnDelete();$t->date('trip_date');$t->string('trip_type');$t->string('event');$t->timestamp('event_at');$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->string('source')->default('manual');$t->foreignId('recorded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['transport_allocation_id','trip_date','trip_type','event'],'boarding_event_unique');});
 if(!Schema::hasTable('vehicle_locations'))Schema::create('vehicle_locations',function(Blueprint $t){$t->id();$t->foreignId('vehicle_id')->constrained()->cascadeOnDelete();$t->decimal('latitude',10,7);$t->decimal('longitude',10,7);$t->decimal('speed',8,2)->nullable();$t->decimal('heading',8,2)->nullable();$t->timestamp('recorded_at');$t->timestamps();$t->index(['vehicle_id','recorded_at']);});
 if(!Schema::hasTable('transport_geofence_events'))Schema::create('transport_geofence_events',function(Blueprint $t){$t->id();$t->foreignId('vehicle_id')->constrained()->cascadeOnDelete();$t->foreignId('transport_stop_id')->constrained()->cascadeOnDelete();$t->string('event');$t->timestamp('event_at');$t->boolean('guardian_notified')->default(false);$t->timestamps();});
 if(!Schema::hasTable('transport_fee_charges'))Schema::create('transport_fee_charges',function(Blueprint $t){$t->id();$t->foreignId('transport_allocation_id')->constrained()->cascadeOnDelete();$t->string('billing_month',7);$t->decimal('amount',10,2);$t->string('status')->default('unpaid');$t->timestamp('paid_at')->nullable();$t->timestamps();$t->unique(['transport_allocation_id','billing_month'],'transport_fee_month_unique');});
 Schema::create('vehicle_expenses',function(Blueprint $t){$t->id();$t->foreignId('vehicle_id')->constrained()->cascadeOnDelete();$t->date('date');$t->string('category');$t->decimal('amount',12,2);$t->string('reference')->nullable();$t->text('notes')->nullable();$t->foreignId('recorded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
}public function down():void{foreach(['vehicle_expenses','transport_fee_charges','transport_geofence_events','vehicle_locations','student_boarding_attendances','transport_personnel_documents','vehicle_maintenance_logs','vehicle_fuel_logs','transport_stops','transport_vehicle_personnel','transport_personnel'] as $x)Schema::dropIfExists($x);Schema::table('vehicles',function(Blueprint $t){$t->dropConstrainedForeignId('transport_route_id');$t->dropColumn(['tracking_token_hash','insurance_expires_at','fitness_expires_at','registration_expires_at']);});}};
