<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 if(!Schema::hasColumn('guardians','phone_verified_at'))Schema::table('guardians',function(Blueprint $t){$t->timestamp('phone_verified_at')->nullable();$t->json('notification_preferences')->nullable();$t->string('emergency_contact_name')->nullable();$t->string('emergency_contact_phone')->nullable();$t->unsignedTinyInteger('emergency_priority')->default(1);});
 if(!Schema::hasColumn('parent_consents','expires_at'))Schema::table('parent_consents',function(Blueprint $t){$t->dateTime('expires_at')->nullable();$t->string('signature_name')->nullable();$t->string('ip_address',45)->nullable();});
 if(!Schema::hasTable('student_clearances'))Schema::create('student_clearances',function(Blueprint $t){$t->id();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->string('department');$t->string('status')->default('pending');$t->decimal('amount_due',12,2)->default(0);$t->text('remarks')->nullable();$t->foreignId('cleared_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('cleared_at')->nullable();$t->timestamps();$t->unique(['student_id','department']);});
 if(!Schema::hasTable('guardian_communication_events'))Schema::create('guardian_communication_events',function(Blueprint $t){$t->id();$t->foreignId('guardian_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->nullable()->constrained()->nullOnDelete();$t->string('channel');$t->string('direction')->default('outbound');$t->string('subject')->nullable();$t->text('content');$t->string('status')->default('recorded');$t->json('meta')->nullable();$t->timestamps();});
 if(!Schema::hasTable('push_subscriptions'))Schema::create('push_subscriptions',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('endpoint_hash',64);$t->text('endpoint');$t->text('public_key')->nullable();$t->text('auth_token')->nullable();$t->string('device_name')->nullable();$t->timestamp('last_used_at')->nullable();$t->timestamps();$t->unique(['user_id','endpoint_hash'],'push_user_endpoint_unique');});
}public function down():void{Schema::dropIfExists('push_subscriptions');Schema::dropIfExists('guardian_communication_events');Schema::dropIfExists('student_clearances');Schema::table('parent_consents',fn(Blueprint $t)=>$t->dropColumn(['expires_at','signature_name','ip_address']));Schema::table('guardians',fn(Blueprint $t)=>$t->dropColumn(['phone_verified_at','notification_preferences','emergency_contact_name','emergency_contact_phone','emergency_priority']));}};
