<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::create('custom_reports',function(Blueprint$t){$t->id();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('data_source');$t->json('columns');$t->json('filters')->nullable();$t->string('group_by')->nullable();$t->string('status')->default('active');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('scheduled_reports',function(Blueprint$t){$t->id();$t->foreignId('custom_report_id')->constrained()->cascadeOnDelete();$t->string('frequency');$t->string('delivery_channel')->default('email');$t->text('recipients');$t->string('format')->default('csv');$t->timestamp('next_run_at');$t->timestamp('last_run_at')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('report_exports',function(Blueprint$t){$t->id();$t->foreignId('custom_report_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->string('format');$t->string('file_path');$t->unsignedInteger('row_count')->default(0);$t->string('status')->default('completed');$t->foreignId('exported_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('exported_at');$t->timestamps();});
 Schema::create('import_batches',function(Blueprint$t){$t->id();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->string('entity_type');$t->string('file_name');$t->string('status')->default('validating');$t->unsignedInteger('total_rows')->default(0);$t->unsignedInteger('valid_rows')->default(0);$t->unsignedInteger('invalid_rows')->default(0);$t->json('errors')->nullable();$t->json('created_ids')->nullable();$t->timestamp('rolled_back_at')->nullable();$t->foreignId('imported_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('kpi_targets',function(Blueprint$t){$t->id();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('metric');$t->decimal('target_value',14,2);$t->string('period');$t->date('starts_at');$t->date('ends_at');$t->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete();$t->string('status')->default('active');$t->timestamps();});
 Schema::create('administration_activities',function(Blueprint$t){$t->id();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('type');$t->string('subject_type')->nullable();$t->unsignedBigInteger('subject_id')->nullable();$t->text('description');$t->json('metadata')->nullable();$t->timestamp('occurred_at');$t->timestamps();$t->index(['subject_type','subject_id']);});
}public function down():void{foreach(['administration_activities','kpi_targets','import_batches','report_exports','scheduled_reports','custom_reports']as$x)Schema::dropIfExists($x);}};
