<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\{DB,Schema};
return new class extends Migration{
 public function up():void{
  Schema::table('payments',function(Blueprint$t){$t->foreignId('campus_id')->nullable()->after('id')->constrained()->nullOnDelete();$t->foreignId('invoice_id')->nullable()->after('fee_assignment_id')->constrained('invoices')->nullOnDelete();$t->decimal('refunded_amount',12,2)->default(0)->after('amount_paid');$t->index(['campus_id','payment_date']);});
  Schema::table('payment_transactions',function(Blueprint$t){$t->foreignId('campus_id')->nullable()->after('id')->constrained()->nullOnDelete();$t->decimal('refunded_amount',12,2)->default(0)->after('amount');$t->index(['campus_id','transaction_date']);});
  Schema::table('payment_refunds',fn(Blueprint$t)=>$t->foreignId('campus_id')->nullable()->after('id')->constrained()->nullOnDelete());
  Schema::create('payment_allocations',function(Blueprint$t){$t->id();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('payment_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('payment_transaction_id')->constrained()->cascadeOnDelete();$t->foreignId('invoice_id')->constrained()->restrictOnDelete();$t->decimal('amount',12,2);$t->decimal('refunded_amount',12,2)->default(0);$t->timestamps();$t->unique(['payment_transaction_id','invoice_id']);});
  DB::table('payments')->whereNull('campus_id')->orderBy('id')->eachById(fn($r)=>DB::table('payments')->where('id',$r->id)->update(['campus_id'=>DB::table('students')->where('id',$r->student_id)->value('campus_id')]));
  DB::table('payment_transactions')->whereNull('campus_id')->orderBy('id')->eachById(function($r){$campus=$r->student_id?DB::table('students')->where('id',$r->student_id)->value('campus_id'):null;if(!$campus&&$r->source_type===App\Models\Invoice::class)$campus=DB::table('invoices')->where('id',$r->source_id)->value('campus_id');if(!$campus&&$r->source_type===App\Models\Payment::class)$campus=DB::table('payments')->where('id',$r->source_id)->value('campus_id');DB::table('payment_transactions')->where('id',$r->id)->update(['campus_id'=>$campus]);});
  DB::table('payment_refunds')->whereNull('campus_id')->orderBy('id')->eachById(fn($r)=>DB::table('payment_refunds')->where('id',$r->id)->update(['campus_id'=>DB::table('payment_transactions')->where('id',$r->payment_transaction_id)->value('campus_id')]));
 }
 public function down():void{Schema::dropIfExists('payment_allocations');Schema::table('payment_refunds',fn(Blueprint$t)=>$t->dropConstrainedForeignId('campus_id'));Schema::table('payment_transactions',function(Blueprint$t){$t->dropIndex(['campus_id','transaction_date']);$t->dropConstrainedForeignId('campus_id');$t->dropColumn('refunded_amount');});Schema::table('payments',function(Blueprint$t){$t->dropIndex(['campus_id','payment_date']);$t->dropConstrainedForeignId('invoice_id');$t->dropConstrainedForeignId('campus_id');$t->dropColumn('refunded_amount');});}
};
