<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::table('saas_plans',function(Blueprint$t){$t->json('feature_limits')->nullable();$t->unsignedInteger('max_campuses')->default(1);$t->unsignedInteger('max_students')->default(500);$t->unsignedInteger('storage_limit_mb')->default(1024);});
 Schema::table('saas_tenants',function(Blueprint$t){$t->foreignId('saas_plan_id')->nullable()->constrained()->nullOnDelete();$t->string('tenant_key',36)->nullable()->unique();$t->string('domain_verification_token')->nullable();$t->timestamp('domain_verified_at')->nullable();$t->timestamp('suspended_at')->nullable();$t->text('suspension_reason')->nullable();});
 Schema::table('campuses',function(Blueprint$t){$t->foreignId('saas_tenant_id')->nullable()->constrained()->nullOnDelete();});
 Schema::table('saas_backups',function(Blueprint$t){$t->foreignId('saas_tenant_id')->nullable()->constrained()->nullOnDelete();});
 Schema::create('tenant_usage_metrics',function(Blueprint$t){$t->id();$t->foreignId('saas_tenant_id')->constrained()->cascadeOnDelete();$t->date('metric_date');$t->string('metric');$t->decimal('value',16,2);$t->timestamps();$t->unique(['saas_tenant_id','metric_date','metric']);});
 Schema::create('tenant_billing_invoices',function(Blueprint$t){$t->id();$t->foreignId('saas_tenant_id')->constrained()->cascadeOnDelete();$t->string('invoice_no')->unique();$t->date('period_start');$t->date('period_end');$t->date('due_date');$t->decimal('amount',12,2);$t->string('currency',10)->default('BDT');$t->string('status')->default('unpaid');$t->timestamp('paid_at')->nullable();$t->string('payment_reference')->nullable();$t->timestamps();});
}public function down():void{Schema::dropIfExists('tenant_billing_invoices');Schema::dropIfExists('tenant_usage_metrics');Schema::table('saas_backups',fn(Blueprint$t)=>$t->dropConstrainedForeignId('saas_tenant_id'));Schema::table('campuses',fn(Blueprint$t)=>$t->dropConstrainedForeignId('saas_tenant_id'));Schema::table('saas_tenants',function(Blueprint$t){$t->dropConstrainedForeignId('saas_plan_id');$t->dropColumn(['tenant_key','domain_verification_token','domain_verified_at','suspended_at','suspension_reason']);});Schema::table('saas_plans',fn(Blueprint$t)=>$t->dropColumn(['feature_limits','max_campuses','max_students','storage_limit_mb']));}};
