<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  foreach(['authors','publishers','categories'] as $name)if(!Schema::hasTable('library_'.$name))Schema::create('library_'.$name,function(Blueprint $t){$t->id();$t->string('name')->unique();$t->text('description')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  if(!Schema::hasColumn('books','author_id'))Schema::table('books',function(Blueprint $t){$t->foreignId('author_id')->nullable()->constrained('library_authors')->nullOnDelete();$t->foreignId('publisher_id')->nullable()->constrained('library_publishers')->nullOnDelete();$t->foreignId('category_id')->nullable()->constrained('library_categories')->nullOnDelete();$t->string('shelf_location')->nullable();});
  if(!Schema::hasTable('book_copies'))Schema::create('book_copies',function(Blueprint $t){$t->id();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('book_id')->constrained()->cascadeOnDelete();$t->string('accession_no')->unique();$t->string('barcode')->unique();$t->string('qr_code')->unique();$t->string('status')->default('available');$t->string('condition')->default('good');$t->date('acquired_at')->nullable();$t->decimal('purchase_price',10,2)->nullable();$t->text('notes')->nullable();$t->timestamps();});
  if(!Schema::hasTable('library_members'))Schema::create('library_members',function(Blueprint $t){$t->id();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('card_no')->unique();$t->string('barcode')->unique();$t->date('valid_until')->nullable();$t->unsignedSmallInteger('max_books')->default(3);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['campus_id','user_id']);});
  if(!Schema::hasColumn('book_issues','book_copy_id'))Schema::table('book_issues',function(Blueprint $t){$t->foreignId('book_copy_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('library_member_id')->nullable()->constrained()->nullOnDelete();$t->decimal('replacement_charge',10,2)->default(0);$t->decimal('fine_paid',10,2)->default(0);$t->string('condition_on_return')->nullable();$t->timestamp('last_reminded_at')->nullable();});
  if(!Schema::hasTable('library_fine_payments'))Schema::create('library_fine_payments',function(Blueprint $t){$t->id();$t->foreignId('book_issue_id')->constrained()->cascadeOnDelete();$t->decimal('amount',10,2);$t->string('payment_method');$t->string('transaction_id')->nullable();$t->foreignId('received_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('paid_at');$t->timestamps();});
  if(!Schema::hasTable('library_stock_checks'))Schema::create('library_stock_checks',function(Blueprint $t){$t->id();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->string('reference_no')->unique();$t->string('status')->default('open');$t->foreignId('started_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('started_at');$t->timestamp('completed_at')->nullable();$t->timestamps();});
  if(!Schema::hasTable('library_stock_check_items'))Schema::create('library_stock_check_items',function(Blueprint $t){$t->id();$t->foreignId('library_stock_check_id')->constrained()->cascadeOnDelete();$t->foreignId('book_copy_id')->constrained()->cascadeOnDelete();$t->string('result')->default('found');$t->string('observed_condition')->nullable();$t->timestamp('scanned_at');$t->unique(['library_stock_check_id','book_copy_id'],'library_stock_copy_unique');});
  if(DB::table('book_copies')->count()===0)DB::table('books')->orderBy('id')->chunkById(100,function($books){foreach($books as $book)for($i=1;$i<=$book->qty;$i++)DB::table('book_copies')->insert(['book_id'=>$book->id,'accession_no'=>'ACC-'.str_pad($book->id,5,'0',STR_PAD_LEFT).'-'.str_pad($i,3,'0',STR_PAD_LEFT),'barcode'=>'LIB'.str_pad($book->id,7,'0',STR_PAD_LEFT).str_pad($i,3,'0',STR_PAD_LEFT),'qr_code'=>'BOOK-'.$book->id.'-'.$i,'status'=>$i<=$book->available?'available':'issued','condition'=>'good','created_at'=>now(),'updated_at'=>now()]);});
 }
 public function down():void{Schema::dropIfExists('library_stock_check_items');Schema::dropIfExists('library_stock_checks');Schema::dropIfExists('library_fine_payments');if(Schema::hasColumn('book_issues','book_copy_id'))Schema::table('book_issues',function(Blueprint $t){$t->dropConstrainedForeignId('book_copy_id');$t->dropConstrainedForeignId('library_member_id');$t->dropColumn(['replacement_charge','fine_paid','condition_on_return','last_reminded_at']);});Schema::dropIfExists('library_members');Schema::dropIfExists('book_copies');if(Schema::hasColumn('books','author_id'))Schema::table('books',function(Blueprint $t){$t->dropConstrainedForeignId('author_id');$t->dropConstrainedForeignId('publisher_id');$t->dropConstrainedForeignId('category_id');$t->dropColumn('shelf_location');});Schema::dropIfExists('library_categories');Schema::dropIfExists('library_publishers');Schema::dropIfExists('library_authors');}
};
