<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::table('sms_templates',function(Blueprint $t){$t->string('channel')->default('sms');$t->string('subject')->nullable();$t->decimal('estimated_cost_per_segment',10,4)->default(0);});
 Schema::create('audience_segments',function(Blueprint $t){$t->id();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('audience_type');$t->json('rules')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('communication_preferences',function(Blueprint $t){$t->id();$t->string('recipient_type');$t->unsignedBigInteger('recipient_id');$t->string('channel');$t->string('category')->default('*');$t->boolean('is_opted_in')->default(true);$t->string('source')->default('portal');$t->timestamp('changed_at')->nullable();$t->timestamps();$t->unique(['recipient_type','recipient_id','channel','category'],'communication_preference_unique');});
 Schema::create('communication_campaigns',function(Blueprint $t){$t->id();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('audience_segment_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('sms_template_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('channel');$t->string('category')->default('general');$t->string('subject')->nullable();$t->text('body');$t->json('audience_rules')->nullable();$t->dateTime('scheduled_at')->nullable();$t->string('status')->default('draft');$t->unsignedInteger('recipient_count')->default(0);$t->unsignedInteger('sent_count')->default(0);$t->unsignedInteger('failed_count')->default(0);$t->unsignedInteger('skipped_count')->default(0);$t->unsignedInteger('total_segments')->default(0);$t->decimal('estimated_cost',12,4)->default(0);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();});
 Schema::create('communication_deliveries',function(Blueprint $t){$t->id();$t->foreignId('communication_campaign_id')->constrained()->cascadeOnDelete();$t->string('recipient_type');$t->unsignedBigInteger('recipient_id')->nullable();$t->string('recipient_name')->nullable();$t->string('destination');$t->string('channel');$t->string('status')->default('queued');$t->unsignedSmallInteger('segments')->default(1);$t->decimal('estimated_cost',10,4)->default(0);$t->string('provider_message_id')->nullable()->index();$t->text('provider_response')->nullable();$t->unsignedTinyInteger('attempts')->default(0);$t->timestamp('delivered_at')->nullable();$t->timestamp('failed_at')->nullable();$t->timestamps();$t->unique(['communication_campaign_id','channel','destination'],'campaign_destination_unique');});
 Schema::create('communication_provider_statuses',function(Blueprint $t){$t->id();$t->string('channel')->unique();$t->decimal('balance',12,4)->nullable();$t->string('currency',10)->nullable();$t->string('status')->default('unknown');$t->text('last_response')->nullable();$t->timestamp('checked_at')->nullable();$t->timestamps();});
}public function down():void{Schema::dropIfExists('communication_provider_statuses');Schema::dropIfExists('communication_deliveries');Schema::dropIfExists('communication_campaigns');Schema::dropIfExists('communication_preferences');Schema::dropIfExists('audience_segments');Schema::table('sms_templates',fn(Blueprint $t)=>$t->dropColumn(['channel','subject','estimated_cost_per_segment']));}};
