import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router } from '@inertiajs/react';
import { useState } from 'react';
const name=x=>x?.student?`${x.student.first_name} ${x.student.last_name||''} (${x.student.admission_no})`:'Student';
const Btn=({onClick,children,tone='emerald'})=><button onClick={onClick} className={`rounded-lg px-3 py-1.5 text-xs font-bold text-white ${tone==='rose'?'bg-rose-600':'bg-emerald-700'}`}>{children}</button>;
const Card=({title,children})=><section className="overflow-x-auto rounded-2xl border bg-white"><h2 className="border-b p-4 font-bold">{title}</h2>{children}</section>;
export default function Index(p){const[tab,setTab]=useState('homework');const patch=(routeName,id,data)=>router.patch(route(routeName,id),data,{preserveScroll:true});return <AuthenticatedLayout><Head title="Student Service Reviews"/><main className="space-y-5 p-4 sm:p-6"><div><h1 className="text-2xl font-bold">Student Service Reviews</h1><p className="text-sm text-slate-500">Homework, leave, attendance, profile এবং library requests</p></div><div className="flex gap-2 overflow-x-auto">{['homework','leaves','corrections','profiles','reservations'].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-lg px-3 py-2 text-xs font-bold capitalize ${tab===x?'bg-indigo-600 text-white':'bg-white border'}`}>{x}</button>)}</div>
{tab==='homework'&&<Card title="Homework Evaluation"><table className="min-w-full text-sm"><tbody>{p.homework.map(x=><tr key={x.id} className="border-t"><td className="p-3">{name(x)}</td><td className="p-3"><b>{x.homework?.title}</b><small className="block text-slate-500">{x.answer||'File submission'}</small></td><td className="p-3">{x.status}</td><td className="p-3 text-right"><Btn onClick={()=>{const marks=prompt(`Marks (max ${x.homework.total_marks})`,x.marks_obtained||'');const feedback=prompt('Feedback',x.teacher_feedback||'');if(marks!==null)patch('admin.student-services.homework',x.id,{marks_obtained:marks,teacher_feedback:feedback,status:'Evaluated'})}}>Evaluate</Btn></td></tr>)}</tbody></table></Card>}
{tab==='leaves'&&<Card title="Leave Requests"><table className="min-w-full text-sm"><tbody>{p.leaves.map(x=><tr key={x.id} className="border-t"><td className="p-3">{name(x)}</td><td className="p-3">{x.leave_type}: {x.start_date}–{x.end_date}<small className="block">{x.reason}</small></td><td>{x.school_status}</td><td className="p-3 space-x-2 text-right"><Btn onClick={()=>patch('admin.student-services.leave',x.id,{status:'Approved'})}>Approve</Btn><Btn tone="rose" onClick={()=>patch('admin.student-services.leave',x.id,{status:'Rejected'})}>Reject</Btn></td></tr>)}</tbody></table></Card>}
{tab==='corrections'&&<Card title="Attendance Corrections"><table className="min-w-full text-sm"><tbody>{p.corrections.map(x=><tr key={x.id} className="border-t"><td className="p-3">{name(x)}</td><td className="p-3">{x.attendance_date}: {x.current_status||'none'} → {x.requested_status}<small className="block">{x.reason}</small></td><td>{x.status}</td><td className="p-3 space-x-2 text-right"><Btn onClick={()=>patch('admin.student-services.correction',x.id,{status:'Approved'})}>Apply</Btn><Btn tone="rose" onClick={()=>patch('admin.student-services.correction',x.id,{status:'Rejected'})}>Reject</Btn></td></tr>)}</tbody></table></Card>}
{tab==='profiles'&&<Card title="Profile Update Requests"><table className="min-w-full text-sm"><tbody>{p.profiles.map(x=><tr key={x.id} className="border-t"><td className="p-3">{name(x)}</td><td className="p-3"><pre className="whitespace-pre-wrap">{JSON.stringify(x.changes,null,2)}</pre></td><td>{x.status}</td><td className="p-3 space-x-2 text-right"><Btn onClick={()=>patch('admin.student-services.profile',x.id,{status:'Approved'})}>Approve</Btn><Btn tone="rose" onClick={()=>patch('admin.student-services.profile',x.id,{status:'Rejected'})}>Reject</Btn></td></tr>)}</tbody></table></Card>}
{tab==='reservations'&&<Card title="Library Reservations"><table className="min-w-full text-sm"><tbody>{p.reservations.map(x=><tr key={x.id} className="border-t"><td className="p-3">User #{x.user_id}</td><td className="p-3">{x.book?.title}</td><td>{x.status}</td><td className="p-3 space-x-2 text-right"><Btn onClick={()=>patch('admin.student-services.reservation',x.id,{status:'Approved'})}>Approve</Btn><Btn tone="rose" onClick={()=>patch('admin.student-services.reservation',x.id,{status:'Rejected'})}>Reject</Btn></td></tr>)}</tbody></table></Card>}</main></AuthenticatedLayout>}
