<?php
namespace App\Http\Controllers;
use App\Models\{Invoice,PaymentGateway,PaymentTransaction};
use App\Services\{AccountingService,FeePaymentService,SslCommerzService};
use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class SslCommerzPaymentController extends Controller{
 public function initiate(Request$r,Invoice$i,SslCommerzService$g){$s=$r->user()->student;abort_unless($s&&(int)$i->student_id===(int)$s->id,403);$due=max(0,(float)$i->amount+(float)$i->fine-(float)$i->discount-(float)$i->paid_amount);abort_if($due<=0,422,'This invoice is already paid.');$amount=(float)$r->validate(['amount'=>['required','numeric','min:10','max:'.$due]])['amount'];$tid='SSL-'.now()->format('YmdHis').'-'.Str::upper(Str::random(8));$provider=PaymentGateway::firstOrCreate(['slug'=>'sslcommerz'],['name'=>'SSLCommerz','currency'=>'BDT','mode'=>config('services.sslcommerz.sandbox')?'sandbox':'live','is_active'=>true]);$url=$g->createSession($i,$s->loadMissing('guardian'),$tid,$amount);PaymentTransaction::create(['campus_id'=>$i->campus_id,'payment_gateway_id'=>$provider->id,'transaction_id'=>$tid,'reference_no'=>$i->invoice_no,'amount'=>$amount,'currency'=>'BDT','payment_method'=>'SSLCommerz','status'=>'Pending','transaction_date'=>today(),'source_type'=>Invoice::class,'source_id'=>$i->id,'student_id'=>$s->id]);return inertia()->location($url);}
 public function success(Request$r,SslCommerzService$g,FeePaymentService$p){$data=$r->validate(['val_id'=>'required|string','tran_id'=>'required|string']);$v=$g->validate($data['val_id']);abort_unless(in_array($v['status']??'',['VALID','VALIDATED'],true),422,'Payment was not verified.');$tx=PaymentTransaction::withoutGlobalScopes()->where('transaction_id',$data['tran_id'])->firstOrFail();abort_unless(hash_equals((string)$tx->transaction_id,(string)($v['tran_id']??''))&&abs((float)$tx->amount-(float)($v['amount']??0))<.01&&strtoupper($v['currency']??'')==='BDT',422,'Payment details do not match.');DB::transaction(function()use($tx,$v,$p){$tx=PaymentTransaction::withoutGlobalScopes()->whereKey($tx->id)->lockForUpdate()->firstOrFail();if($tx->status==='Completed')return;abort_unless($tx->status==='Pending',422,'This transaction can no longer be completed.');$p->applyOnlinePayment($tx);$tx->update(['status'=>'Completed','note'=>'SSLCommerz bank transaction: '.($v['bank_tran_id']??'N/A')]);app(AccountingService::class)->post('online-payment:'.$tx->id,$tx,'1000','4000',(float)$tx->amount,'Online fee payment '.$tx->transaction_id,now()->toDateString(),'Receipt');},3);return redirect()->route('portal.services',['tab'=>'fees'])->with('success','Payment completed successfully.');}
 public function failed(){return redirect()->route('portal.services',['tab'=>'fees'])->with('error','Payment was not completed. Its status will be reconciled securely.');}
}
