<?php
namespace App\Http\Controllers\Admin;use App\Http\Controllers\Controller;use App\Models\{AudienceSegment,CommunicationCampaign,SmsTemplate};use App\Services\{CommunicationCampaignService,MessageMetrics};use Illuminate\Http\Request;use Illuminate\Support\Facades\{DB,Http};use Illuminate\Validation\Rule;use Inertia\Inertia;
class CommunicationCenterController extends Controller{
 public function index(){return Inertia::render('Admin/Communication/Center',['templates'=>SmsTemplate::latest()->get(),'segments'=>AudienceSegment::latest()->get(),'campaigns'=>CommunicationCampaign::with('deliveries')->latest()->take(100)->get(),'providers'=>DB::table('communication_provider_statuses')->get()]);}
 public function template(Request $r){$d=$r->validate(['id'=>'nullable|exists:sms_templates,id','key'=>'required|string|max:100','name'=>'required|string|max:255','channel'=>'required|in:sms,email,whatsapp,push','category'=>'required|string|max:80','subject'=>'nullable|string|max:255','body'=>'required|string|max:5000','estimated_cost_per_segment'=>'numeric|min:0','is_active'=>'boolean','auto_send'=>'boolean']);SmsTemplate::updateOrCreate(['id'=>$d['id']??null],collect($d)->except('id')->all());return back()->with('success','Template saved.');}
 public function segment(Request $r){$d=$r->validate(['name'=>'required|string|max:255','audience_type'=>'required|in:students,guardians,staff','rules'=>'nullable|array']);AudienceSegment::create($d);return back()->with('success','Audience segment saved.');}
 public function campaign(Request $r){$d=$r->validate(['name'=>'required|string|max:255','channel'=>'required|in:sms,email,whatsapp,push','category'=>'required|string|max:80','subject'=>'nullable|string|max:255','body'=>'required|string|max:5000','audience_segment_id'=>'nullable|exists:audience_segments,id','audience_rules'=>'nullable|array','scheduled_at'=>'nullable|date']);CommunicationCampaign::create($d+['status'=>'draft','created_by'=>$r->user()->id]);return back()->with('success','Campaign saved as draft.');}
 public function approve(Request $r,CommunicationCampaign $campaign){abort_unless($campaign->status==='draft',422,'Only drafts can be approved.');$campaign->update(['status'=>$campaign->scheduled_at?'scheduled':'approved','approved_by'=>$r->user()->id,'approved_at'=>now()]);return back()->with('success','Campaign approved.');}
 public function dispatch(CommunicationCampaign $campaign,CommunicationCampaignService $s){$result=$s->queue($campaign);return back()->with('success',"{$result['queued']} deliveries queued; {$result['skipped']} skipped.");}
 public function metrics(Request $r){$d=$r->validate(['message'=>'nullable|string','rate'=>'nullable|numeric|min:0']);return response()->json(MessageMetrics::calculate($d['message']??'',(float)($d['rate']??config('services.sms.cost_per_segment',0))));}
 public function balance(){foreach(['sms','whatsapp','push'] as $channel){$cfg=config("services.$channel");try{$url=$cfg['balance_url']??null;if(!$url)throw new \RuntimeException('Balance endpoint not configured');$res=Http::timeout(15)->withToken($cfg['api_key']??'')->get($url)->throw();$balance=$res->json('balance');DB::table('communication_provider_statuses')->updateOrInsert(['channel'=>$channel],['balance'=>$balance,'currency'=>$res->json('currency','BDT'),'status'=>'online','last_response'=>$res->body(),'checked_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);}catch(\Throwable $e){DB::table('communication_provider_statuses')->updateOrInsert(['channel'=>$channel],['status'=>'unavailable','last_response'=>$e->getMessage(),'checked_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);}}return back()->with('success','Provider balances checked.');}
 public function preference(Request $r){$d=$r->validate(['recipient_type'=>'required|in:student,guardian,staff','recipient_id'=>'required|integer','channel'=>'required|in:sms,email,whatsapp,push','category'=>'required|string|max:80','is_opted_in'=>'required|boolean']);DB::table('communication_preferences')->updateOrInsert(collect($d)->only(['recipient_type','recipient_id','channel','category'])->all(),$d+['changed_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Communication consent updated.');}
}
