<?php
namespace App\Http\Controllers\Admin;use App\Http\Controllers\Controller;use App\Models\{Book,BookCopy,BookIssue,LibraryFinePayment,LibraryMember,LibraryReservation,User};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;use Inertia\Inertia;
class LibraryOperationsController extends Controller{
 public function index(){return Inertia::render('Admin/LibraryOperations/Index',['books'=>Book::with('copies')->orderBy('title')->get(),'copies'=>BookCopy::with('book:id,title')->latest()->take(200)->get(),'members'=>LibraryMember::with('user:id,name,email')->latest()->take(200)->get(),'reservations'=>LibraryReservation::with(['book:id,title'])->latest()->take(100)->get(),'issues'=>BookIssue::with(['book:id,title','copy','user:id,name'])->latest()->take(150)->get(),'stockChecks'=>DB::table('library_stock_checks')->latest()->take(30)->get(),'masters'=>['authors'=>DB::table('library_authors')->orderBy('name')->get(),'publishers'=>DB::table('library_publishers')->orderBy('name')->get(),'categories'=>DB::table('library_categories')->orderBy('name')->get()],'users'=>User::orderBy('name')->get(['id','name','email'])]);}
 public function master(Request $r){$d=$r->validate(['type'=>'required|in:authors,publishers,categories','name'=>'required|string|max:255','description'=>'nullable|string|max:1000']);DB::table('library_'.$d['type'])->updateOrInsert(['name'=>$d['name']],['description'=>$d['description']??null,'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Library master saved.');}
 public function copy(Request $r){$d=$r->validate(['book_id'=>'required|exists:books,id','accession_no'=>'required|string|max:100|unique:book_copies','barcode'=>'nullable|string|max:100|unique:book_copies','acquired_at'=>'nullable|date','purchase_price'=>'nullable|numeric|min:0','condition'=>'required|in:new,good,fair,damaged']);$d['barcode']=$d['barcode']?:'LIB-'.strtoupper(bin2hex(random_bytes(5)));$d['qr_code']='BOOK:'.$d['barcode'];BookCopy::create($d+['status'=>'available']);Book::where('id',$d['book_id'])->incrementEach(['qty'=>1,'available'=>1]);return back()->with('success','Book accession/copy added.');}
 public function member(Request $r){$d=$r->validate(['user_id'=>'required|exists:users,id','card_no'=>'required|string|max:100|unique:library_members','barcode'=>'nullable|string|max:100|unique:library_members','valid_until'=>'nullable|date','max_books'=>'required|integer|min:1|max:20']);$d['barcode']=$d['barcode']?:'MEM-'.strtoupper(bin2hex(random_bytes(5)));LibraryMember::create($d+['is_active'=>true]);return back()->with('success','Library member card created.');}
 public function scan(Request $r){$d=$r->validate(['code'=>'required|string|max:255']);$copy=BookCopy::with('book')->where('barcode',$d['code'])->orWhere('qr_code',$d['code'])->orWhere('accession_no',$d['code'])->first();$member=LibraryMember::with('user:id,name,email')->where('barcode',$d['code'])->orWhere('card_no',$d['code'])->first();return response()->json(['copy'=>$copy,'member'=>$member]);}
 public function issue(Request $r){$d=$r->validate(['book_copy_id'=>'required|exists:book_copies,id','library_member_id'=>'required|exists:library_members,id','issue_date'=>'required|date','due_date'=>'required|date|after_or_equal:issue_date']);DB::transaction(function()use($d){$copy=BookCopy::lockForUpdate()->findOrFail($d['book_copy_id']);$member=LibraryMember::findOrFail($d['library_member_id']);abort_unless($copy->status==='available',422,'Copy is not available.');abort_unless($member->is_active&&(!$member->valid_until||$member->valid_until->endOfDay()->isFuture()),422,'Member card is inactive or expired.');abort_if(BookIssue::where('library_member_id',$member->id)->whereIn('status',['Issued','Overdue'])->count()>=$member->max_books,422,'Member issue limit reached.');BookIssue::create($d+['book_id'=>$copy->book_id,'user_id'=>$member->user_id,'campus_id'=>$copy->campus_id,'status'=>'Issued']);$copy->update(['status'=>'issued']);$copy->book()->decrement('available');});return back()->with('success','Book issued by scanned copy/card.');}
 public function returnBook(Request $r,BookIssue $issue){$d=$r->validate(['condition_on_return'=>'required|in:good,fair,damaged,lost','replacement_charge'=>'nullable|numeric|min:0']);DB::transaction(function()use($issue,$d){$copy=BookCopy::lockForUpdate()->find($issue->book_copy_id);$lost=$d['condition_on_return']==='lost';$damaged=$d['condition_on_return']==='damaged';$issue->update(['return_date'=>today(),'condition_on_return'=>$d['condition_on_return'],'replacement_charge'=>$d['replacement_charge']??0,'status'=>$lost?'Lost':'Returned']);if($copy){$copy->update(['status'=>$lost?'lost':($damaged?'damaged':'available'),'condition'=>$d['condition_on_return']]);if(!$lost&&!$damaged)$copy->book()->increment('available');}});return back()->with('success','Return/lost/damaged processing completed.');}
 public function reservation(Request $r,LibraryReservation $reservation){$d=$r->validate(['status'=>'required|in:Approved,Rejected,Fulfilled,Cancelled','note'=>'nullable|string|max:1000']);if($d['status']==='Approved')abort_unless(BookCopy::where('book_id',$reservation->book_id)->where('status','available')->exists(),422,'No copy is currently available.');$reservation->update($d+['expires_at'=>$d['status']==='Approved'?today()->addDays(3):$reservation->expires_at]);return back()->with('success','Reservation updated.');}
 public function finePayment(Request $r,BookIssue $issue){$d=$r->validate(['amount'=>'required|numeric|min:0.01','payment_method'=>'required|in:Cash,Bank,Mobile Banking,Online','transaction_id'=>'nullable|string|max:255']);$due=max(0,$issue->fine_amount+$issue->replacement_charge-$issue->fine_paid);abort_if($d['amount']>$due,422,'Payment exceeds outstanding library charge.');DB::transaction(function()use($issue,$d,$r){LibraryFinePayment::create($d+['book_issue_id'=>$issue->id,'received_by'=>$r->user()->id,'paid_at'=>now()]);$issue->increment('fine_paid',$d['amount']);});return back()->with('success','Library fine/charge payment received.');}
 public function startStock(Request $r){$id=DB::table('library_stock_checks')->insertGetId(['campus_id'=>config('app.active_campus_id'),'reference_no'=>'STOCK-'.now()->format('YmdHis'),'status'=>'open','started_by'=>$r->user()->id,'started_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Physical stock check started: #'.$id);}
 public function scanStock(Request $r,int $check){$d=$r->validate(['code'=>'required|string|max:255','condition'=>'required|in:new,good,fair,damaged']);$copy=BookCopy::where('barcode',$d['code'])->orWhere('qr_code',$d['code'])->orWhere('accession_no',$d['code'])->firstOrFail();DB::table('library_stock_check_items')->updateOrInsert(['library_stock_check_id'=>$check,'book_copy_id'=>$copy->id],['result'=>'found','observed_condition'=>$d['condition'],'scanned_at'=>now()]);return back()->with('success','Copy counted.');}
 public function completeStock(int $check){DB::transaction(function()use($check){$seen=DB::table('library_stock_check_items')->where('library_stock_check_id',$check)->pluck('book_copy_id');BookCopy::whereNotIn('id',$seen)->whereNotIn('status',['issued','lost'])->update(['status'=>'missing']);DB::table('library_stock_checks')->where('id',$check)->update(['status'=>'completed','completed_at'=>now(),'updated_at'=>now()]);});return back()->with('success','Stock check completed; unscanned copies marked missing.');}
}
