<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\{HealthRecord,MedicineStock,Student,User,Vaccination};use App\Services\{MalwareScanner,SmsService};use Illuminate\Http\Request;use Illuminate\Support\Facades\{DB,Storage};use Illuminate\Validation\ValidationException;use Inertia\Inertia;
class MedicalOperationsController extends Controller{
 public function index(){return Inertia::render('Admin/MedicalOperations/Index',['people'=>User::with(['student:id,user_id,guardian_id,first_name,last_name,admission_no','staff:id,user_id,first_name,last_name,staff_id_no'])->orderBy('name')->get(['id','name','email']),'students'=>Student::with('guardian:id,father_name,father_phone')->where('status',true)->get(['id','user_id','guardian_id','first_name','last_name','admission_no']),'profiles'=>HealthRecord::with('user:id,name')->get(),'medicines'=>MedicineStock::with('room:id,room_number')->orderBy('medicine_name')->get(),'issues'=>DB::table('medicine_issues')->latest('issued_at')->take(100)->get(),'appointments'=>DB::table('doctor_appointments')->latest('scheduled_at')->take(100)->get(),'consents'=>DB::table('medical_consents')->latest()->take(100)->get(),'alerts'=>DB::table('medical_emergency_alerts')->latest('occurred_at')->take(100)->get(),'documents'=>DB::table('medical_documents')->latest()->take(100)->get(),'vaccinations'=>Vaccination::with('student:id,name')->whereNotNull('next_due_date')->orderBy('next_due_date')->take(100)->get(),'summary'=>['emergencyProfiles'=>HealthRecord::where('emergency_alert',true)->count(),'lowStock'=>MedicineStock::whereColumn('quantity','<=','reorder_level')->count(),'appointmentsToday'=>DB::table('doctor_appointments')->whereDate('scheduled_at',today())->where('status','scheduled')->count(),'vaccinesDue'=>Vaccination::whereBetween('next_due_date',[today(),today()->addDays(30)])->count()]]);}
 public function profile(Request $r){$d=$r->validate(['user_id'=>'required|exists:users,id','blood_group'=>'nullable|string|max:10','allergies'=>'nullable|string','chronic_conditions'=>'nullable|string','emergency_contact'=>'nullable|string|max:100','emergency_alert'=>'boolean','emergency_instructions'=>'nullable|string']);HealthRecord::updateOrCreate(['user_id'=>$d['user_id']],$d+['campus_id'=>config('app.active_campus_id'),'data_classification'=>'restricted','last_updated_by'=>$r->user()->id]);return back()->with('success','Restricted medical profile updated.');}
 public function consent(Request $r){$d=$r->validate(['student_id'=>'required|exists:students,id','consent_type'=>'required|in:general_treatment,medicine,emergency_transfer,vaccination,procedure','is_granted'=>'boolean','valid_from'=>'required|date','valid_until'=>'nullable|date|after_or_equal:valid_from','restrictions'=>'nullable|string','signed_name'=>'required|string|max:255']);$student=Student::findOrFail($d['student_id']);DB::table('medical_consents')->insert($d+['guardian_id'=>$student->guardian_id,'signed_at'=>now(),'recorded_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Guardian medical consent recorded.');}
 public function issue(Request $r){$d=$r->validate(['medicine_stock_id'=>'required|exists:medicine_stocks,id','user_id'=>'required|exists:users,id','quantity'=>'required|integer|min:1','dosage'=>'nullable|string|max:255','prescribed_by'=>'nullable|string|max:255','reason'=>'nullable|string']);DB::transaction(function()use($d,$r){$stock=MedicineStock::lockForUpdate()->findOrFail($d['medicine_stock_id']);if($stock->expiry_date&&$stock->expiry_date->isPast())throw ValidationException::withMessages(['medicine_stock_id'=>'Expired medicine cannot be issued.']);if($stock->quantity<$d['quantity'])throw ValidationException::withMessages(['quantity'=>'Insufficient medicine stock.']);$stock->decrement('quantity',$d['quantity']);DB::table('medicine_issues')->insert($d+['issued_at'=>now(),'issued_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);});return back()->with('success','Medicine issued and stock ledger updated.');}
 public function appointment(Request $r){$d=$r->validate(['user_id'=>'required|exists:users,id','doctor_name'=>'required|string|max:255','scheduled_at'=>'required|date','location'=>'nullable|string|max:255','reason'=>'nullable|string']);DB::table('doctor_appointments')->insert($d+['status'=>'scheduled','created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Doctor appointment scheduled.');}
 public function appointmentStatus(Request $r,int $appointment){$d=$r->validate(['status'=>'required|in:scheduled,confirmed,completed,cancelled,no_show','outcome'=>'nullable|string']);DB::table('doctor_appointments')->where('id',$appointment)->update($d+['updated_at'=>now()]);return back()->with('success','Appointment updated.');}
 public function emergency(Request $r){$d=$r->validate(['user_id'=>'required|exists:users,id','severity'=>'required|in:moderate,serious,critical','message'=>'required|string|max:1000','location'=>'nullable|string|max:255']);$user=User::with('student.guardian')->findOrFail($d['user_id']);$id=DB::table('medical_emergency_alerts')->insertGetId($d+['occurred_at'=>now(),'reported_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);$phone=$user->student?->guardian?->father_phone;$sent=$phone&&SmsService::send($phone,"MEDICAL {$d['severity']}: {$user->name}. {$d['message']} Location: ".($d['location']?:'School').'. Contact school immediately.',['category'=>'medical_emergency','reference_key'=>'medical-emergency:'.$id]);DB::table('medical_emergency_alerts')->where('id',$id)->update(['guardian_notified'=>(bool)$sent]);return back()->with($sent?'success':'warning',$sent?'Emergency recorded and guardian notified.':'Emergency recorded; guardian phone was unavailable or SMS failed.');}
 public function document(Request $r,MalwareScanner $scanner){$d=$r->validate(['user_id'=>'required|exists:users,id','title'=>'required|string|max:255','document_type'=>'required|string|max:100','document_date'=>'nullable|date','visibility'=>'required|in:medical_only,guardian,student','file'=>'required|file|mimes:pdf,jpg,jpeg,png|max:5120']);$scanner->assertClean($r->file('file'));$path=$r->file('file')->store('medical/restricted','local');unset($d['file']);DB::table('medical_documents')->insert($d+['file_path'=>$path,'uploaded_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Scanned restricted medical document uploaded.');}
 public function download(Request $r,int $document){$doc=DB::table('medical_documents')->where('id',$document)->first();abort_unless($doc,404);abort_unless($r->user()->hasRole('Super Admin')||$r->user()->can('admin.medical.operations'),403);abort_unless(Storage::disk('local')->exists($doc->file_path),404);return Storage::disk('local')->download($doc->file_path,basename($doc->title).'.'.pathinfo($doc->file_path,PATHINFO_EXTENSION));}
}
