<?php
namespace App\Http\Controllers\Admin;use App\Http\Controllers\Controller;use App\Models\{Campus,SaasBackup,SaasPlan,SaasTenant,User};use App\Services\SecureBackupService;use Illuminate\Http\Request;use Illuminate\Support\Facades\{DB,Hash};use Illuminate\Support\Str;use Inertia\Inertia;use Spatie\Permission\Models\Role;
class SaasControlController extends Controller{
 public function index(){return Inertia::render('Admin/SaaS/Control/Index',['tenants'=>SaasTenant::with(['plan','campuses'])->latest()->get(),'plans'=>SaasPlan::where('is_active',true)->get(),'usage'=>DB::table('tenant_usage_metrics')->latest('metric_date')->take(300)->get(),'invoices'=>DB::table('tenant_billing_invoices')->latest()->take(150)->get(),'backups'=>SaasBackup::whereNotNull('saas_tenant_id')->latest()->take(100)->get(),'report'=>$this->report()]);}
 public function planLimits(Request$r,SaasPlan$plan){$d=$r->validate(['max_campuses'=>'required|integer|min:1','max_students'=>'required|integer|min:1','storage_limit_mb'=>'required|integer|min:10','features'=>'array','features.*'=>'boolean']);$plan->update(['max_campuses'=>$d['max_campuses'],'max_students'=>$d['max_students'],'storage_limit_mb'=>$d['storage_limit_mb'],'feature_limits'=>$d['features']??[]]);return back()->with('success','Plan limits updated.');}
 public function provision(Request$r){$d=$r->validate(['company_name'=>'required|string|max:255','domain'=>'required|string|max:255|unique:saas_tenants,domain','admin_email'=>'required|email|unique:users,email','admin_phone'=>'nullable|string|max:30','saas_plan_id'=>'required|exists:saas_plans,id','valid_until'=>'nullable|date']);$password=Str::password(14);DB::transaction(function()use($d,$password,&$tenant){$plan=SaasPlan::findOrFail($d['saas_plan_id']);$tenant=SaasTenant::create($d+['subscription_plan'=>$plan->name,'status'=>'Active','tenant_key'=>(string)Str::uuid(),'domain_verification_token'=>'erp-verification='.Str::random(32)]);$campus=Campus::create(['saas_tenant_id'=>$tenant->id,'name'=>$d['company_name'].' Main Campus','code'=>'T'.$tenant->id.'-MAIN','email'=>$d['admin_email'],'phone'=>$d['admin_phone']??null,'is_main'=>true,'is_active'=>true]);$user=User::create(['name'=>$d['company_name'].' Administrator','email'=>$d['admin_email'],'password'=>Hash::make($password),'campus_id'=>$campus->id,'password_changed_at'=>now()]);$role=Role::firstOrCreate(['name'=>'Tenant Admin','guard_name'=>'web']);if(\Spatie\Permission\Models\Permission::where('name','dashboard')->exists())$role->givePermissionTo('dashboard');$user->assignRole($role);});return back()->with('success','Tenant provisioned. Temporary password: '.$password.' — copy it now.');}
 public function status(Request$r,SaasTenant$tenant){$d=$r->validate(['status'=>'required|in:Active,Suspended','reason'=>'nullable|string|max:1000']);$tenant->update(['status'=>$d['status'],'suspended_at'=>$d['status']==='Suspended'?now():null,'suspension_reason'=>$d['status']==='Suspended'?($d['reason']??null):null]);return back()->with('success','Tenant status updated.');}
 public function verifyDomain(SaasTenant$tenant){$host=parse_url(str_contains($tenant->domain,'://')?$tenant->domain:'https://'.$tenant->domain,PHP_URL_HOST);$records=@dns_get_record($host,DNS_TXT)?:[];$valid=collect($records)->contains(fn($x)=>str_contains($x['txt']??'',(string)$tenant->domain_verification_token));if($valid)$tenant->update(['domain_verified_at'=>now()]);return back()->with($valid?'success':'error',$valid?'Custom domain verified.':'TXT record not found. Add: '.$tenant->domain_verification_token);}
 public function meter(SaasTenant$tenant){$campuses=$tenant->campuses()->pluck('id');$metrics=['campuses'=>$campuses->count(),'students'=>DB::table('students')->whereIn('campus_id',$campuses)->whereNull('deleted_at')->count(),'staff'=>DB::table('staff')->whereIn('campus_id',$campuses)->whereNull('deleted_at')->count(),'storage_mb'=>$this->storage($campuses)];foreach($metrics as$metric=>$value)DB::table('tenant_usage_metrics')->updateOrInsert(['saas_tenant_id'=>$tenant->id,'metric_date'=>today(),'metric'=>$metric],['value'=>$value,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Tenant usage metered.');}
 public function invoice(Request$r,SaasTenant$tenant){$d=$r->validate(['period_start'=>'required|date','period_end'=>'required|date|after_or_equal:period_start','due_date'=>'required|date','amount'=>'required|numeric|min:0']);DB::table('tenant_billing_invoices')->insert(['saas_tenant_id'=>$tenant->id,'invoice_no'=>'SAAS-'.now()->format('ymd').'-'.$tenant->id.'-'.random_int(100,999),'period_start'=>$d['period_start'],'period_end'=>$d['period_end'],'due_date'=>$d['due_date'],'amount'=>$d['amount'],'currency'=>$tenant->plan?->currency??'BDT','status'=>'unpaid','created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Central billing invoice created.');}
 public function pay(Request$r,int$invoice){$d=$r->validate(['payment_reference'=>'required|string|max:255']);DB::table('tenant_billing_invoices')->where('id',$invoice)->where('status','unpaid')->update(['status'=>'paid','paid_at'=>now(),'payment_reference'=>$d['payment_reference'],'updated_at'=>now()]);return back()->with('success','Subscription invoice marked paid.');}
 public function backup(Request$r,SaasTenant$tenant,SecureBackupService$s){$campuses=$tenant->campuses()->pluck('id')->all();$b=SaasBackup::create(['saas_tenant_id'=>$tenant->id,'file_name'=>'tenant-'.$tenant->id.'-'.now()->format('YmdHis').'.zip','type'=>'Database','status'=>'Pending','created_by'=>$r->user()->id]);try{$s->create($b,$campuses);}catch(\Throwable$e){$b->update(['status'=>'Failed','error_message'=>$e->getMessage()]);return back()->with('error',$e->getMessage());}return back()->with('success','Encrypted tenant-scoped backup created.');}
 private function storage($campuses){$bytes=0;foreach(['student_documents','medical_documents']as$table){if(!\Illuminate\Support\Facades\Schema::hasTable($table)||!\Illuminate\Support\Facades\Schema::hasColumn($table,'campus_id'))continue;foreach(DB::table($table)->whereIn('campus_id',$campuses)->pluck('file_path')as$p){$path=storage_path('app/'.$p);if(is_file($path))$bytes+=filesize($path);}}return round($bytes/1048576,2);}
 private function report(){return SaasTenant::with(['plan','campuses'])->get()->map(function($t){$ids=$t->campuses->pluck('id');return['id'=>$t->id,'tenant'=>$t->company_name,'campuses'=>$ids->count(),'students'=>DB::table('students')->whereIn('campus_id',$ids)->whereNull('deleted_at')->count(),'staff'=>DB::table('staff')->whereIn('campus_id',$ids)->whereNull('deleted_at')->count(),'collection'=>(float)DB::table('invoices')->whereIn('campus_id',$ids)->sum('paid_amount'),'plan'=>$t->plan?->name??$t->subscription_plan,'status'=>$t->status];});}
}
