<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\{SaasBackup,User};use App\Services\SecureBackupService;use Illuminate\Http\Request;use Illuminate\Support\Facades\{Artisan,DB,Hash,Storage};use Inertia\Inertia;use ZipArchive;
class SecurityOperationsController extends Controller{
 public function index(Request$r){$sessions=DB::table('sessions')->leftJoin('users','users.id','=','sessions.user_id')->select('sessions.id','sessions.user_id','users.name','sessions.ip_address','sessions.user_agent','sessions.last_activity')->orderByDesc('sessions.last_activity')->take(200)->get();return Inertia::render('Admin/SecurityOperations/Index',['users'=>User::with('roles:id,name')->get(['id','name','email','two_factor_enabled','password_changed_at','password_expires_days','locked_until']),'sessions'=>$sessions,'backups'=>SaasBackup::latest()->take(50)->get(),'failedJobs'=>DB::table('failed_jobs')->latest('failed_at')->take(100)->get(),'queueCount'=>DB::table('jobs')->count(),'errors'=>DB::table('system_error_events')->latest('occurred_at')->take(100)->get(),'health'=>DB::table('system_health_checks')->latest('checked_at')->take(30)->get(),'retention'=>DB::table('data_retention_runs')->latest('executed_at')->take(30)->get(),'drTests'=>DB::table('disaster_recovery_tests')->latest('tested_at')->take(30)->get()]);}
 public function userPolicy(Request$r,User$user){$d=$r->validate(['two_factor_enabled'=>'boolean','password_expires_days'=>'nullable|integer|min:1|max:365','unlock'=>'boolean']);$user->update(['two_factor_enabled'=>$d['two_factor_enabled']??false,'password_expires_days'=>$d['password_expires_days']??null,'locked_until'=>($d['unlock']??false)?null:$user->locked_until]);return back()->with('success','User security policy updated.');}
 public function revokeSession(Request$r,string$id){abort_if($id===$r->session()->getId(),422,'Current session cannot be revoked here.');DB::table('sessions')->where('id',$id)->delete();return back()->with('success','Session revoked.');}
 public function backup(Request$r,SecureBackupService$s){$d=$r->validate(['type'=>'required|in:Database,Files,Full Backup']);$b=SaasBackup::create(['file_name'=>'backup_'.strtolower(str_replace(' ','_',$d['type'])).'_'.now()->format('Y_m_d_His').'.zip','type'=>$d['type'],'status'=>'Pending','created_by'=>$r->user()->id]);try{$s->create($b);}catch(\Throwable$e){$b->update(['status'=>'Failed','error_message'=>$e->getMessage()]);report($e);return back()->with('error','Backup failed: '.$e->getMessage());}return back()->with('success','Encrypted backup created and checksummed.');}
 public function verify(Request$r,SaasBackup$backup,SecureBackupService$s){$ok=$s->verify($backup);DB::table('disaster_recovery_tests')->insert(['saas_backup_id'=>$backup->id,'status'=>$ok?'passed':'failed','checksum_status'=>$ok?'valid':'invalid','details'=>$ok?'Archive exists and SHA-256 checksum matches.':'Archive missing or checksum mismatch.','tested_at'=>now(),'tested_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with($ok?'success':'error',$ok?'Disaster recovery verification passed.':'Backup verification failed.');}
 public function restore(Request$r,SaasBackup$backup,SecureBackupService$s){$d=$r->validate(['confirmation'=>'required|in:RESTORE','password'=>'required|current_password']);abort_unless($s->verify($backup),422,'Backup checksum failed.');abort_unless(str_contains(strtolower($backup->type),'database')||str_contains(strtolower($backup->type),'full'),422,'Backup has no database payload.');$tmp=tempnam(sys_get_temp_dir(),'erp_restore_');file_put_contents($tmp,Storage::disk($backup->disk)->get($backup->path));$zip=new ZipArchive();abort_unless($zip->open($tmp)===true,422,'Cannot open backup.');$zip->setPassword(config('app.key'));$json=$zip->getFromName('database.json');$zip->close();@unlink($tmp);abort_unless($json,422,'Database payload unavailable.');$payload=json_decode($json,true,512,JSON_THROW_ON_ERROR);DB::transaction(function()use($payload){DB::statement('SET FOREIGN_KEY_CHECKS=0');try{foreach($payload['tables'] as$table=>$rows){if(!\Illuminate\Support\Facades\Schema::hasTable($table)||in_array($table,['migrations','sessions','jobs','failed_jobs']))continue;foreach(array_chunk($rows,200)as$chunk)foreach($chunk as$row)isset($row['id'])?DB::table($table)->updateOrInsert(['id'=>$row['id']],$row):DB::table($table)->insert($row);}}finally{DB::statement('SET FOREIGN_KEY_CHECKS=1');}});DB::table('disaster_recovery_tests')->insert(['saas_backup_id'=>$backup->id,'status'=>'passed','checksum_status'=>'valid','details'=>'Authorized in-place database restore completed.','tested_at'=>now(),'tested_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Database restore completed.');}
 public function health(Request$r){$checks=[];$start=microtime(true);try{DB::select('SELECT 1');$checks[]=['database','healthy',null];}catch(\Throwable$e){$checks[]=['database','critical',$e->getMessage()];}$checks[]=['storage',is_writable(storage_path())?'healthy':'critical',is_writable(storage_path())?null:'Storage is not writable'];$checks[]=['queue',DB::table('failed_jobs')->where('failed_at','>=',now()->subHour())->count()>10?'warning':'healthy','Failed jobs in last hour: '.DB::table('failed_jobs')->where('failed_at','>=',now()->subHour())->count()];foreach($checks as[$component,$status,$message])DB::table('system_health_checks')->insert(['component'=>$component,'status'=>$status,'response_ms'=>(int)((microtime(true)-$start)*1000),'message'=>$message,'checked_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','System health checks completed.');}
 public function retryJob(string$id){Artisan::call('queue:retry',[$id]);return back()->with('success','Failed job queued for retry.');}
 public function retention(Request$r){$d=$r->validate(['scope'=>'required|in:failed_logins,login_history,audit_logs,error_events','retention_days'=>'required|integer|min:30|max:3650','confirm'=>'required|boolean']);$map=['failed_logins'=>['security_failed_logins','attempted_at'],'login_history'=>['security_login_histories','login_at'],'audit_logs'=>['security_audit_logs','created_at'],'error_events'=>['system_error_events','occurred_at']];[$table,$date]=$map[$d['scope']];$count=DB::table($table)->where($date,'<',now()->subDays($d['retention_days']))->count();if($d['confirm'])DB::table($table)->where($date,'<',now()->subDays($d['retention_days']))->delete();DB::table('data_retention_runs')->insert(['scope'=>$d['scope'],'retention_days'=>$d['retention_days'],'records_deleted'=>$d['confirm']?$count:0,'status'=>$d['confirm']?'completed':'preview','details'=>($d['confirm']?'Deleted ':'Would delete ').$count.' records.','executed_by'=>$r->user()->id,'executed_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success',($d['confirm']?'Deleted ':'Preview: ').$count.' records.');}
}
