<?php
namespace App\Http\Controllers\Admin;use App\Http\Controllers\Controller;use App\Models\{TransportAllocation,TransportPersonnel,TransportRoute,TransportStop,Vehicle};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Inertia\Inertia;
class TransportOperationsController extends Controller{
 private function raw(string$table){return DB::table($table)->where($table.'.campus_id',config('app.active_campus_id'));}
 public function index(){return Inertia::render('Admin/TransportOperations/Index',['vehicles'=>Vehicle::with('latestLocation')->get(),'routes'=>TransportRoute::where('is_active',true)->get(),'stops'=>TransportStop::orderBy('sequence')->get(),'personnel'=>TransportPersonnel::latest()->get(),'allocations'=>TransportAllocation::with('user:id,name,email')->where('is_active',true)->get(),'fuelLogs'=>$this->raw('vehicle_fuel_logs')->latest('date')->take(100)->get(),'maintenance'=>$this->raw('vehicle_maintenance_logs')->latest()->take(100)->get(),'documents'=>$this->raw('transport_personnel_documents')->latest()->take(100)->get(),'boarding'=>$this->raw('student_boarding_attendances')->latest('event_at')->take(100)->get(),'fees'=>$this->raw('transport_fee_charges')->latest()->take(100)->get(),'expenses'=>$this->raw('vehicle_expenses')->latest('date')->take(100)->get(),'summary'=>['fuel'=>$this->raw('vehicle_fuel_logs')->selectRaw('COALESCE(SUM(litres*unit_price),0) total')->value('total'),'maintenance'=>$this->raw('vehicle_maintenance_logs')->sum('cost'),'other'=>$this->raw('vehicle_expenses')->sum('amount')]]);}
 public function personnel(Request $r){TransportPersonnel::create($r->validate(['type'=>'required|in:driver,helper','name'=>'required|string|max:255','phone'=>'required|string|max:30','license_no'=>'nullable|string|max:100','license_expires_at'=>'nullable|date','national_id'=>'nullable|string|max:100']));return back()->with('success','Driver/helper saved.');}
 public function assign(Request $r){$d=$r->validate(['vehicle_id'=>'required|exists:vehicles,id','transport_personnel_id'=>'required|exists:transport_personnel,id','assigned_from'=>'required|date','assigned_until'=>'nullable|date|after_or_equal:assigned_from']);$this->raw('transport_vehicle_personnel')->insert($d+['campus_id'=>config('app.active_campus_id'),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Personnel assigned.');}
 public function stop(Request $r){TransportStop::create($r->validate(['transport_route_id'=>'required|exists:transport_routes,id','name'=>'required|string|max:255','sequence'=>'required|integer|min:1','pickup_time'=>'nullable','drop_time'=>'nullable','latitude'=>'nullable|numeric|between:-90,90','longitude'=>'nullable|numeric|between:-180,180','geofence_radius_m'=>'required|integer|min:20|max:5000','monthly_fare'=>'required|numeric|min:0']));return back()->with('success','Stop and schedule saved.');}
 public function fuel(Request $r){$d=$r->validate(['vehicle_id'=>'required|exists:vehicles,id','date'=>'required|date','litres'=>'required|numeric|min:0.01','unit_price'=>'required|numeric|min:0','odometer'=>'nullable|numeric|min:0','vendor'=>'nullable|string|max:255','receipt_no'=>'nullable|string|max:100']);$this->raw('vehicle_fuel_logs')->insert($d+['campus_id'=>config('app.active_campus_id'),'recorded_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Fuel log saved.');}
 public function maintenance(Request $r){$d=$r->validate(['vehicle_id'=>'required|exists:vehicles,id','type'=>'required|string|max:100','service_date'=>'nullable|date','next_due_date'=>'nullable|date','next_due_odometer'=>'nullable|numeric|min:0','cost'=>'numeric|min:0','vendor'=>'nullable|string|max:255','status'=>'required|in:scheduled,in_progress,completed','notes'=>'nullable|string']);$this->raw('vehicle_maintenance_logs')->insert($d+['campus_id'=>config('app.active_campus_id'),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Maintenance saved.');}
 public function document(Request $r){$d=$r->validate(['transport_personnel_id'=>'required|exists:transport_personnel,id','type'=>'required|string|max:100','number'=>'nullable|string|max:100','expires_at'=>'nullable|date','file'=>'nullable|file|max:5120']);$d['file_path']=$r->hasFile('file')?$r->file('file')->store('transport/documents/'.config('app.active_campus_id'),'local'):null;unset($d['file']);$this->raw('transport_personnel_documents')->insert($d+['campus_id'=>config('app.active_campus_id'),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Personnel document saved.');}
 public function boarding(Request $r){$d=$r->validate(['transport_allocation_id'=>'required|exists:transport_allocations,id','trip_date'=>'required|date','trip_type'=>'required|in:pickup,drop','event'=>'required|in:boarded,dropped,absent','latitude'=>'nullable|numeric','longitude'=>'nullable|numeric']);$a=TransportAllocation::findOrFail($d['transport_allocation_id']);$this->raw('student_boarding_attendances')->updateOrInsert(collect($d)->only(['transport_allocation_id','trip_date','trip_type','event'])->all(),$d+['campus_id'=>config('app.active_campus_id'),'vehicle_id'=>$a->vehicle_id,'event_at'=>now(),'source'=>'manual','recorded_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);$this->notify($a,$d['event'],$d['trip_type']);return back()->with('success','Boarding recorded and guardian notified.');}
 public function token(Vehicle $vehicle){$token=bin2hex(random_bytes(24));$vehicle->update(['tracking_token_hash'=>hash('sha256',$token)]);return back()->with('success','GPS token (copy now): '.$token);}
 public function expense(Request $r){$d=$r->validate(['vehicle_id'=>'required|exists:vehicles,id','date'=>'required|date','category'=>'required|string|max:100','amount'=>'required|numeric|min:0','reference'=>'nullable|string|max:100','notes'=>'nullable|string']);$this->raw('vehicle_expenses')->insert($d+['campus_id'=>config('app.active_campus_id'),'recorded_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Vehicle expense saved.');}
 public function generateFees(Request $r){$month=$r->validate(['month'=>'required|date_format:Y-m'])['month'];TransportAllocation::where('is_active',true)->each(fn($a)=>$this->raw('transport_fee_charges')->updateOrInsert(['transport_allocation_id'=>$a->id,'billing_month'=>$month],['campus_id'=>config('app.active_campus_id'),'amount'=>$a->monthly_fare,'status'=>'unpaid','created_at'=>now(),'updated_at'=>now()]));return back()->with('success','Monthly transport fees generated.');}
 private function notify($a,$event,$trip){$u=$a->user;$s=$u?->student;$phone=$s?->guardian?->father_phone;if($phone)\App\Services\SmsService::send($phone,"Transport update: {$u->name} was {$event} for {$trip} at ".now()->format('h:i A').'.',['category'=>'transport','reference_key'=>'transport:'.$a->id.':'.$trip.':'.$event.':'.today()]);}
}
