import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Pagination from '@/Components/Pagination';

const types={counselling:'Counselling',guardian_meeting:'Guardian Meeting',scholarship:'Scholarship',co_curricular:'Co-curricular / Club',achievement:'Achievement / Award',behaviour:'Behaviour Observation',learning_support:'Learning Support',career_guidance:'Career Guidance'};
const blank={student_id:'',record_type:'counselling',record_date:new Date().toISOString().slice(0,10),follow_up_date:'',title:'',period:'',amount:0,score:'',status:'open',details:{},notes:''};

function Form({item,students,close}){
 const {data,setData,post,put,processing,errors}=useForm(item?{...blank,...item,record_date:item.record_date?.slice(0,10),follow_up_date:item.follow_up_date?.slice(0,10)||'',details:item.details||{}}:blank);
 const submit=e=>{e.preventDefault();const o={onSuccess:close,preserveScroll:true};item?put(route('admin.student-development-records.update',item.id),o):post(route('admin.student-development-records.store'),o)};
 const scholarship=data.record_type==='scholarship';
 return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 p-3" onClick={close}><form onSubmit={submit} onClick={e=>e.stopPropagation()} className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-bold">{item?'Edit':'Add'} Student Record</h2><p className="text-sm text-slate-500">Student support, achievement and development</p></div><button type="button" onClick={close}>✕</button></div><div className="grid gap-4 sm:grid-cols-2">
 <label className="text-sm font-semibold">Student<select value={data.student_id} onChange={e=>setData('student_id',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200"><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} ({s.admission_no})</option>)}</select>{errors.student_id&&<small className="text-rose-600">{errors.student_id}</small>}</label>
 <label className="text-sm font-semibold">Record type<select value={data.record_type} onChange={e=>setData('record_type',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200">{Object.entries(types).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label className="text-sm font-semibold">Record date<input type="date" value={data.record_date} onChange={e=>setData('record_date',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200"/></label>
 <label className="text-sm font-semibold">Follow-up date<input type="date" value={data.follow_up_date||''} onChange={e=>setData('follow_up_date',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200"/>{errors.follow_up_date&&<small className="text-rose-600">{errors.follow_up_date}</small>}</label>
 <label className="text-sm font-semibold">Title<input value={data.title} onChange={e=>setData('title',e.target.value)} placeholder="Session / activity / achievement title" className="mt-1 w-full rounded-xl border-slate-200"/>{errors.title&&<small className="text-rose-600">{errors.title}</small>}</label>
 <label className="text-sm font-semibold">Period<input value={data.period||''} onChange={e=>setData('period',e.target.value)} placeholder="e.g. Session 2026" className="mt-1 w-full rounded-xl border-slate-200"/></label>
 {scholarship&&<label className="text-sm font-semibold">Scholarship amount<input type="number" min="0" step=".01" value={data.amount} onChange={e=>setData('amount',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200"/></label>}
 {['behaviour','learning_support','co_curricular'].includes(data.record_type)&&<label className="text-sm font-semibold">Score / progress (%)<input type="number" min="0" max="100" value={data.score} onChange={e=>setData('score',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200"/></label>}
 <label className="text-sm font-semibold">Status<select value={data.status} onChange={e=>setData('status',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200">{['open','in_progress','resolved','awarded','completed','cancelled'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select></label>
 <label className="text-sm font-semibold sm:col-span-2">Notes<textarea rows="4" value={data.notes||''} onChange={e=>setData('notes',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200"/></label>
 </div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-xl border px-5 py-2.5">Cancel</button><button disabled={processing} className="rounded-xl bg-emerald-800 px-6 py-2.5 font-semibold text-white">Save Record</button></div></form></div>
}

export default function Index({records,studentList,filters,summary}){
 const [open,setOpen]=useState(false),[edit,setEdit]=useState(null);const filter=(key,value)=>router.get(route('admin.student-development-records.index'),{...filters,[key]:value},{preserveState:true,replace:true});
 return <AuthenticatedLayout><Head title="Student Development"/><div className="space-y-6 py-8 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Students · Development</p><h1 className="text-2xl font-bold text-slate-900">Student Development & Support</h1><p className="text-sm text-slate-500">Counselling, scholarship, activities, achievements and learning support.</p></div><button onClick={()=>{setEdit(null);setOpen(true)}} className="rounded-xl bg-emerald-800 px-5 py-2.5 font-semibold text-white">+ Add Student Record</button></div>
 <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{Object.entries(types).map(([k,l])=><button key={k} onClick={()=>filter('type',filters.type===k?'':k)} className={`rounded-xl border p-4 text-left ${filters.type===k?'border-emerald-700 bg-emerald-50':'bg-white'}`}><b className="block text-2xl">{summary[k]||0}</b><span className="text-xs text-slate-500">{l}</span></button>)}</div>
 <div className="flex flex-col gap-3 rounded-xl border bg-white p-3 sm:flex-row"><input defaultValue={filters.search||''} onKeyDown={e=>e.key==='Enter'&&filter('search',e.currentTarget.value)} placeholder="Search student, admission no. or title..." className="flex-1 rounded-xl border-slate-200"/><select value={filters.student_id||''} onChange={e=>filter('student_id',e.target.value)} className="rounded-xl border-slate-200"><option value="">All students</option>{studentList.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name}</option>)}</select></div>
 <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Date','Student','Type / Title','Follow-up','Amount / Score','Status','Actions'].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody className="divide-y">{records.data.map(r=><tr key={r.id}><td className="px-5 py-4">{r.record_date}</td><td className="px-5 py-4 font-semibold">{r.student?.first_name} {r.student?.last_name}<small className="block text-slate-400">{r.student?.admission_no}</small></td><td className="px-5 py-4"><b>{types[r.record_type]}</b><small className="block text-slate-500">{r.title}</small></td><td className="px-5 py-4">{r.follow_up_date||'—'}</td><td className="px-5 py-4">{r.record_type==='scholarship'?`৳ ${r.amount}`:r.score?`${r.score}%`:'—'}</td><td className="px-5 py-4 capitalize">{r.status?.replace('_',' ')}</td><td className="px-5 py-4"><button onClick={()=>{setEdit(r);setOpen(true)}} className="mr-3 text-amber-700">Edit</button><button onClick={()=>confirm('Delete this record?')&&router.delete(route('admin.student-development-records.destroy',r.id))} className="text-rose-700">Delete</button></td></tr>)}{!records.data.length&&<tr><td colSpan="7" className="p-10 text-center text-slate-500">No student development records found.</td></tr>}</tbody></table><div className="border-t p-4"><Pagination meta={records}/></div></div></div>{open&&<Form item={edit} students={studentList} close={()=>setOpen(false)}/>}</AuthenticatedLayout>
}
