import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Pagination from '@/Components/Pagination';

function GenerateForm({classes,subjects,close}){
 const {data,setData,post,processing,errors}=useForm({school_class_id:'',subject_id:'',exam_name:'',exam_date:new Date().toISOString().slice(0,10),duration_minutes:60,question_count:10,question_type:'',instructions:'Answer all questions. Write clearly and show necessary working.',shuffle:true});
 const submit=e=>{e.preventDefault();post(route('admin.lms.question-papers.store'),{onSuccess:close,preserveScroll:true})};
 const input='mt-1 w-full rounded-xl border-slate-200 bg-slate-50 text-sm';
 return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 p-3" onClick={close}><form onSubmit={submit} onClick={e=>e.stopPropagation()} className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-6 flex justify-between"><div><h2 className="text-xl font-bold">Auto Generate Question Paper</h2><p className="text-sm text-slate-500">Question Bank থেকে random অথবা serial প্রশ্ন নিয়ে paper তৈরি হবে।</p></div><button type="button" onClick={close}>✕</button></div><div className="grid gap-4 sm:grid-cols-2">
 <label className="text-sm font-semibold">Class<select value={data.school_class_id} onChange={e=>setData('school_class_id',e.target.value)} className={input}><option value="">Select class</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{errors.school_class_id&&<small className="text-rose-600">{errors.school_class_id}</small>}</label>
 <label className="text-sm font-semibold">Subject<select value={data.subject_id} onChange={e=>setData('subject_id',e.target.value)} className={input}><option value="">Select subject</option>{subjects.map(x=><option key={x.id} value={x.id}>{x.name} {x.code&&`(${x.code})`}</option>)}</select>{errors.subject_id&&<small className="text-rose-600">{errors.subject_id}</small>}</label>
 <label className="text-sm font-semibold sm:col-span-2">Examination name<input value={data.exam_name} onChange={e=>setData('exam_name',e.target.value)} placeholder="e.g. Half Yearly Examination 2026" className={input}/>{errors.exam_name&&<small className="text-rose-600">{errors.exam_name}</small>}</label>
 <label className="text-sm font-semibold">Exam date<input type="date" value={data.exam_date} onChange={e=>setData('exam_date',e.target.value)} className={input}/></label>
 <label className="text-sm font-semibold">Duration (minutes)<input type="number" min="5" value={data.duration_minutes} onChange={e=>setData('duration_minutes',e.target.value)} className={input}/></label>
 <label className="text-sm font-semibold">Number of questions<input type="number" min="1" max="200" value={data.question_count} onChange={e=>setData('question_count',e.target.value)} className={input}/>{errors.question_count&&<small className="block text-rose-600">{errors.question_count}</small>}</label>
 <label className="text-sm font-semibold">Question type<select value={data.question_type} onChange={e=>setData('question_type',e.target.value)} className={input}><option value="">All question types</option><option value="MCQ">MCQ</option><option value="True/False">True / False</option></select></label>
 <label className="text-sm font-semibold sm:col-span-2">Instructions<textarea rows="3" value={data.instructions} onChange={e=>setData('instructions',e.target.value)} className={input}/></label>
 <label className="flex items-center gap-2 text-sm font-semibold sm:col-span-2"><input type="checkbox" checked={data.shuffle} onChange={e=>setData('shuffle',e.target.checked)}/> Randomize questions each time</label>
 </div><div className="mt-6 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">Full Marks প্রশ্নগুলোর individual marks যোগ করে স্বয়ংক্রিয়ভাবে হিসাব হবে। School name, logo ও address Website Settings থেকে আসবে।</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-xl border px-5 py-2.5">Cancel</button><button disabled={processing} className="rounded-xl bg-emerald-800 px-6 py-2.5 font-semibold text-white">{processing?'Generating...':'Generate Paper'}</button></div></form></div>
}

function Paper({paper,site,close}){
 const duration=`${Math.floor(paper.duration_minutes/60)?`${Math.floor(paper.duration_minutes/60)} hour${Math.floor(paper.duration_minutes/60)>1?'s':''}`:''}${paper.duration_minutes%60?` ${paper.duration_minutes%60} minutes`:''}`;
 return <div className="fixed inset-0 z-[100] overflow-y-auto bg-slate-900/70 p-2 sm:p-6"><style>{`@media print{body *{visibility:hidden}.question-paper,.question-paper *{visibility:visible}.question-paper{position:absolute!important;inset:0!important;width:100%!important;box-shadow:none!important;margin:0!important}.paper-actions{display:none!important}@page{size:A4;margin:14mm}}`}</style><div className="paper-actions mx-auto mb-3 flex max-w-[210mm] justify-end gap-2"><button onClick={close} className="rounded-lg bg-white px-4 py-2">Close</button><button onClick={()=>window.print()} className="rounded-lg bg-emerald-800 px-5 py-2 font-semibold text-white">Print / Save PDF</button></div><article className="question-paper mx-auto min-h-[297mm] max-w-[210mm] bg-white p-6 text-black shadow-2xl sm:p-12">
 <header className="border-b-2 border-black pb-4 text-center">{site.logo&&<img src={site.logo} className="mx-auto mb-2 h-16 max-w-24 object-contain"/>}<h1 className="text-2xl font-bold">{site.school_name}</h1>{site.address&&<p className="text-xs">{site.address}</p>}<h2 className="mt-3 text-lg font-bold uppercase">{paper.exam_name}</h2><p className="text-sm">Subject: <b>{paper.subject?.name}</b> · Class: <b>{paper.school_class?.name}</b></p></header>
 <div className="my-3 flex flex-wrap justify-between border-b border-black pb-3 text-sm"><span>Date: <b>{paper.exam_date||'________________'}</b></span><span>Time: <b>{duration}</b></span><span>Full Marks: <b>{Number(paper.full_marks)}</b></span></div>
 {paper.instructions&&<div className="mb-5 border border-black p-3 text-sm"><b>Instructions:</b> {paper.instructions}</div>}
 <ol className="space-y-5">{paper.questions.map((q,i)=><li key={`${q.id}-${i}`} className="break-inside-avoid"><div className="flex gap-3"><b>{i+1}.</b><div className="flex-1"><div className="flex justify-between gap-3"><span>{q.question}</span><b className="whitespace-nowrap">[{q.marks}]</b></div>{q.options?.length>0&&<div className="mt-2 grid grid-cols-2 gap-x-6 gap-y-1 text-sm">{q.options.map((o,j)=><span key={j}>({String.fromCharCode(97+j)}) {o}</span>)}</div>}</div></div></li>)}</ol>
 <footer className="mt-12 flex justify-between border-t border-black pt-8 text-xs"><span>Paper Code: {paper.paper_code}</span><span>Examiner's Signature: __________________</span></footer>
 </article></div>
}

export default function Index({papers,classes,subjects,siteSettings,filters}){
 const [form,setForm]=useState(false),[preview,setPreview]=useState(null);
 return <AuthenticatedLayout><Head title="Question Paper Generator"/><div className="space-y-6 py-8 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">LMS · Question Bank</p><h1 className="text-2xl font-bold">Question Paper Generator</h1><p className="text-sm text-slate-500">Automatic school header, marks calculation, preview and A4 print.</p></div><button onClick={()=>setForm(true)} className="rounded-xl bg-emerald-800 px-5 py-2.5 font-semibold text-white">+ Generate Question Paper</button></div>
 <input defaultValue={filters.search||''} onKeyDown={e=>e.key==='Enter'&&router.get(route('admin.lms.question-papers.index'),{search:e.currentTarget.value})} placeholder="Search exam name or paper code..." className="w-full rounded-xl border-slate-200 bg-white"/>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{papers.data.map(p=><div key={p.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><span className="rounded bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-800">{p.paper_code}</span><span className="text-xs text-slate-400">{p.exam_date}</span></div><h3 className="mt-4 font-bold text-slate-900">{p.exam_name}</h3><p className="mt-1 text-sm text-slate-500">{p.school_class?.name} · {p.subject?.name}</p><div className="mt-4 flex gap-4 border-y py-3 text-sm"><span>Questions: <b>{p.questions.length}</b></span><span>Marks: <b>{Number(p.full_marks)}</b></span><span>Time: <b>{p.duration_minutes}m</b></span></div><div className="mt-4 flex justify-end gap-3"><button onClick={()=>setPreview(p)} className="font-semibold text-emerald-800">Preview / Print</button><button onClick={()=>confirm('Delete this question paper?')&&router.delete(route('admin.lms.question-papers.destroy',p.id))} className="text-rose-700">Delete</button></div></div>)}{!papers.data.length&&<div className="col-span-full rounded-2xl border bg-white p-12 text-center text-slate-500">No generated question papers yet.</div>}</div><Pagination meta={papers}/></div>{form&&<GenerateForm classes={classes} subjects={subjects} close={()=>setForm(false)}/>} {preview&&<Paper paper={preview} site={siteSettings} close={()=>setPreview(null)}/>}</AuthenticatedLayout>
}
