import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Pagination from '@/Components/Pagination';

const types = { promotion: 'Staff Promotion', pf: 'Provident Fund (PF)', gf: 'Gratuity Fund (GF)', class_performance: 'Class Performance', training: 'Teacher Training', certification: 'Certification', award: 'Award / Recognition', disciplinary: 'Disciplinary Record', transfer: 'Transfer / Posting' };
const empty = { staff_id: '', record_type: 'promotion', record_date: new Date().toISOString().slice(0,10), title: '', period: '', employee_amount: 0, employer_amount: 0, rating: '', status: 'draft', details: {}, notes: '' };

function RecordForm({ item, staffList, close }) {
  const { data, setData, post, put, processing, errors } = useForm(item ? { ...empty, ...item, record_date: item.record_date?.slice(0,10), details: item.details || {} } : empty);
  const submit = e => { e.preventDefault(); const done = { onSuccess: close, preserveScroll: true }; item ? put(route('admin.staff-hr-records.update', item.id), done) : post(route('admin.staff-hr-records.store'), done); };
  const fund = ['pf','gf'].includes(data.record_type);
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/60 p-3" onClick={close}><form onSubmit={submit} onClick={e=>e.stopPropagation()} className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-bold">{item ? 'Edit' : 'Add'} HR Record</h2><p className="text-sm text-slate-500">Promotion, fund, performance or training record</p></div><button type="button" onClick={close}>✕</button></div><div className="grid gap-4 sm:grid-cols-2">
    <label className="text-sm font-semibold">Staff<select value={data.staff_id} onChange={e=>setData('staff_id',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200"><option value="">Select staff</option>{staffList.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} ({s.staff_id_no})</option>)}</select>{errors.staff_id&&<small className="text-rose-600">{errors.staff_id}</small>}</label>
    <label className="text-sm font-semibold">Record type<select value={data.record_type} onChange={e=>setData('record_type',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200">{Object.entries(types).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <label className="text-sm font-semibold">Date<input type="date" value={data.record_date} onChange={e=>setData('record_date',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200" /></label>
    <label className="text-sm font-semibold">Title<input value={data.title} onChange={e=>setData('title',e.target.value)} placeholder="Course / promotion / evaluation title" className="mt-1 w-full rounded-xl border-slate-200" />{errors.title&&<small className="text-rose-600">{errors.title}</small>}</label>
    <label className="text-sm font-semibold">Period<input value={data.period||''} onChange={e=>setData('period',e.target.value)} placeholder="e.g. 2026 or Jan–Jun" className="mt-1 w-full rounded-xl border-slate-200" /></label>
    <label className="text-sm font-semibold">Status<select value={data.status} onChange={e=>setData('status',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200">{['draft','pending','approved','completed','cancelled'].map(x=><option key={x}>{x}</option>)}</select></label>
    {fund && <><label className="text-sm font-semibold">Employee contribution<input type="number" min="0" step=".01" value={data.employee_amount} onChange={e=>setData('employee_amount',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200" /></label><label className="text-sm font-semibold">Employer contribution<input type="number" min="0" step=".01" value={data.employer_amount} onChange={e=>setData('employer_amount',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200" /></label></>}
    {data.record_type==='class_performance' && <label className="text-sm font-semibold">Performance score (%)<input type="number" min="0" max="100" value={data.rating} onChange={e=>setData('rating',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200" /></label>}
    <label className="text-sm font-semibold sm:col-span-2">Notes<textarea rows="3" value={data.notes||''} onChange={e=>setData('notes',e.target.value)} className="mt-1 w-full rounded-xl border-slate-200" /></label>
  </div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-xl border px-5 py-2.5">Cancel</button><button disabled={processing} className="rounded-xl bg-emerald-800 px-6 py-2.5 font-semibold text-white">Save Record</button></div></form></div>;
}

export default function Index({ records, staffList, filters, summary }) {
  const [form, setForm] = useState(false); const [edit, setEdit] = useState(null);
  const filter = (key,value) => router.get(route('admin.staff-hr-records.index'), {...filters,[key]:value}, {preserveState:true,replace:true});
  return <AuthenticatedLayout><Head title="Teacher & Staff HR"/><div className="space-y-6 py-8 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">People · Teacher HR</p><h1 className="text-2xl font-bold text-slate-900">Teacher & Staff Development</h1><p className="text-sm text-slate-500">Promotion, PF/GF, class performance and training records.</p></div><button onClick={()=>{setEdit(null);setForm(true)}} className="rounded-xl bg-emerald-800 px-5 py-2.5 font-semibold text-white">+ Add HR Record</button></div>
  <div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5">{Object.entries(types).map(([key,label])=><button key={key} onClick={()=>filter('type',filters.type===key?'':key)} className={`rounded-xl border p-4 text-left ${filters.type===key?'border-emerald-700 bg-emerald-50':'bg-white'}`}><span className="block text-2xl font-bold text-slate-900">{summary[key]||0}</span><span className="text-xs text-slate-500">{label}</span></button>)}</div>
  <div className="flex flex-col gap-3 rounded-xl border bg-white p-3 sm:flex-row"><input defaultValue={filters.search||''} onKeyDown={e=>e.key==='Enter'&&filter('search',e.currentTarget.value)} placeholder="Search staff or title..." className="flex-1 rounded-xl border-slate-200"/><select value={filters.staff_id||''} onChange={e=>filter('staff_id',e.target.value)} className="rounded-xl border-slate-200"><option value="">All staff</option>{staffList.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name}</option>)}</select></div>
  <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Date','Staff','Type / Title','Financial / Score','Status','Actions'].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody className="divide-y">{records.data.map(r=><tr key={r.id}><td className="px-5 py-4">{r.record_date}</td><td className="px-5 py-4 font-semibold">{r.staff?.first_name} {r.staff?.last_name}<small className="block text-slate-400">{r.staff?.staff_id_no}</small></td><td className="px-5 py-4"><b>{types[r.record_type]}</b><small className="block text-slate-500">{r.title}</small></td><td className="px-5 py-4">{['pf','gf'].includes(r.record_type)?`৳ ${Number(r.employee_amount)+Number(r.employer_amount)}`:r.rating?`${r.rating}%`:'—'}</td><td className="px-5 py-4 capitalize">{r.status}</td><td className="px-5 py-4"><button onClick={()=>{setEdit(r);setForm(true)}} className="mr-3 text-amber-700">Edit</button><button onClick={()=>confirm('Delete this record?')&&router.delete(route('admin.staff-hr-records.destroy',r.id))} className="text-rose-700">Delete</button></td></tr>)}{!records.data.length&&<tr><td colSpan="6" className="p-10 text-center text-slate-500">No HR records found.</td></tr>}</tbody></table><div className="border-t p-4"><Pagination meta={records}/></div></div></div>{form&&<RecordForm item={edit} staffList={staffList} close={()=>setForm(false)}/>}</AuthenticatedLayout>;
}
